// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ActorProtocol.proto
// Protobuf C++ Version: 5.29.3

#ifndef ActorProtocol_2eproto_2epb_2eh
#define ActorProtocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ActorProtocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ActorProtocol_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ActorProtocol_2eproto;
namespace GameProtocol {
class C_Move;
struct C_MoveDefaultTypeInternal;
extern C_MoveDefaultTypeInternal _C_Move_default_instance_;
class C_Spawn;
struct C_SpawnDefaultTypeInternal;
extern C_SpawnDefaultTypeInternal _C_Spawn_default_instance_;
class S_Move;
struct S_MoveDefaultTypeInternal;
extern S_MoveDefaultTypeInternal _S_Move_default_instance_;
class S_Spawn;
struct S_SpawnDefaultTypeInternal;
extern S_SpawnDefaultTypeInternal _S_Spawn_default_instance_;
}  // namespace GameProtocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace GameProtocol {

// ===================================================================


// -------------------------------------------------------------------

class S_Spawn final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.S_Spawn) */ {
 public:
  inline S_Spawn() : S_Spawn(nullptr) {}
  ~S_Spawn() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_Spawn* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_Spawn));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_Spawn(
      ::google::protobuf::internal::ConstantInitialized);

  inline S_Spawn(const S_Spawn& from) : S_Spawn(nullptr, from) {}
  inline S_Spawn(S_Spawn&& from) noexcept
      : S_Spawn(nullptr, std::move(from)) {}
  inline S_Spawn& operator=(const S_Spawn& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Spawn& operator=(S_Spawn&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Spawn& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Spawn* internal_default_instance() {
    return reinterpret_cast<const S_Spawn*>(
        &_S_Spawn_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(S_Spawn& a, S_Spawn& b) { a.Swap(&b); }
  inline void Swap(S_Spawn* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Spawn* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Spawn* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_Spawn>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_Spawn& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_Spawn& from) { S_Spawn::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_Spawn* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.S_Spawn"; }

 protected:
  explicit S_Spawn(::google::protobuf::Arena* arena);
  S_Spawn(::google::protobuf::Arena* arena, const S_Spawn& from);
  S_Spawn(::google::protobuf::Arena* arena, S_Spawn&& from) noexcept
      : S_Spawn(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNewLocationFieldNumber = 2,
    kNewRotationFieldNumber = 3,
    kPawnClassFieldNumber = 1,
  };
  // .GameProtocol.Location NewLocation = 2;
  bool has_newlocation() const;
  void clear_newlocation() ;
  const ::GameProtocol::Location& newlocation() const;
  PROTOBUF_NODISCARD ::GameProtocol::Location* release_newlocation();
  ::GameProtocol::Location* mutable_newlocation();
  void set_allocated_newlocation(::GameProtocol::Location* value);
  void unsafe_arena_set_allocated_newlocation(::GameProtocol::Location* value);
  ::GameProtocol::Location* unsafe_arena_release_newlocation();

  private:
  const ::GameProtocol::Location& _internal_newlocation() const;
  ::GameProtocol::Location* _internal_mutable_newlocation();

  public:
  // .GameProtocol.Rotation NewRotation = 3;
  bool has_newrotation() const;
  void clear_newrotation() ;
  const ::GameProtocol::Rotation& newrotation() const;
  PROTOBUF_NODISCARD ::GameProtocol::Rotation* release_newrotation();
  ::GameProtocol::Rotation* mutable_newrotation();
  void set_allocated_newrotation(::GameProtocol::Rotation* value);
  void unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value);
  ::GameProtocol::Rotation* unsafe_arena_release_newrotation();

  private:
  const ::GameProtocol::Rotation& _internal_newrotation() const;
  ::GameProtocol::Rotation* _internal_mutable_newrotation();

  public:
  // int32 PawnClass = 1;
  void clear_pawnclass() ;
  ::int32_t pawnclass() const;
  void set_pawnclass(::int32_t value);

  private:
  ::int32_t _internal_pawnclass() const;
  void _internal_set_pawnclass(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.S_Spawn)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S_Spawn& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::GameProtocol::Location* newlocation_;
    ::GameProtocol::Rotation* newrotation_;
    ::int32_t pawnclass_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ActorProtocol_2eproto;
};
// -------------------------------------------------------------------

class S_Move final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.S_Move) */ {
 public:
  inline S_Move() : S_Move(nullptr) {}
  ~S_Move() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_Move* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_Move));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_Move(
      ::google::protobuf::internal::ConstantInitialized);

  inline S_Move(const S_Move& from) : S_Move(nullptr, from) {}
  inline S_Move(S_Move&& from) noexcept
      : S_Move(nullptr, std::move(from)) {}
  inline S_Move& operator=(const S_Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Move& operator=(S_Move&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Move* internal_default_instance() {
    return reinterpret_cast<const S_Move*>(
        &_S_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(S_Move& a, S_Move& b) { a.Swap(&b); }
  inline void Swap(S_Move* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Move* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Move* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_Move>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_Move& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_Move& from) { S_Move::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_Move* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.S_Move"; }

 protected:
  explicit S_Move(::google::protobuf::Arena* arena);
  S_Move(::google::protobuf::Arena* arena, const S_Move& from);
  S_Move(::google::protobuf::Arena* arena, S_Move&& from) noexcept
      : S_Move(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNewCoordinateFieldNumber = 2,
    kNewRotationFieldNumber = 3,
    kActorIdFieldNumber = 1,
  };
  // .GameProtocol.Location NewCoordinate = 2;
  bool has_newcoordinate() const;
  void clear_newcoordinate() ;
  const ::GameProtocol::Location& newcoordinate() const;
  PROTOBUF_NODISCARD ::GameProtocol::Location* release_newcoordinate();
  ::GameProtocol::Location* mutable_newcoordinate();
  void set_allocated_newcoordinate(::GameProtocol::Location* value);
  void unsafe_arena_set_allocated_newcoordinate(::GameProtocol::Location* value);
  ::GameProtocol::Location* unsafe_arena_release_newcoordinate();

  private:
  const ::GameProtocol::Location& _internal_newcoordinate() const;
  ::GameProtocol::Location* _internal_mutable_newcoordinate();

  public:
  // .GameProtocol.Rotation NewRotation = 3;
  bool has_newrotation() const;
  void clear_newrotation() ;
  const ::GameProtocol::Rotation& newrotation() const;
  PROTOBUF_NODISCARD ::GameProtocol::Rotation* release_newrotation();
  ::GameProtocol::Rotation* mutable_newrotation();
  void set_allocated_newrotation(::GameProtocol::Rotation* value);
  void unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value);
  ::GameProtocol::Rotation* unsafe_arena_release_newrotation();

  private:
  const ::GameProtocol::Rotation& _internal_newrotation() const;
  ::GameProtocol::Rotation* _internal_mutable_newrotation();

  public:
  // int32 ActorId = 1;
  void clear_actorid() ;
  ::int32_t actorid() const;
  void set_actorid(::int32_t value);

  private:
  ::int32_t _internal_actorid() const;
  void _internal_set_actorid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.S_Move)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S_Move& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::GameProtocol::Location* newcoordinate_;
    ::GameProtocol::Rotation* newrotation_;
    ::int32_t actorid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ActorProtocol_2eproto;
};
// -------------------------------------------------------------------

class C_Spawn final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.C_Spawn) */ {
 public:
  inline C_Spawn() : C_Spawn(nullptr) {}
  ~C_Spawn() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_Spawn* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_Spawn));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_Spawn(
      ::google::protobuf::internal::ConstantInitialized);

  inline C_Spawn(const C_Spawn& from) : C_Spawn(nullptr, from) {}
  inline C_Spawn(C_Spawn&& from) noexcept
      : C_Spawn(nullptr, std::move(from)) {}
  inline C_Spawn& operator=(const C_Spawn& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Spawn& operator=(C_Spawn&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Spawn& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_Spawn* internal_default_instance() {
    return reinterpret_cast<const C_Spawn*>(
        &_C_Spawn_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(C_Spawn& a, C_Spawn& b) { a.Swap(&b); }
  inline void Swap(C_Spawn* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Spawn* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Spawn* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_Spawn>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_Spawn& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_Spawn& from) { C_Spawn::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_Spawn* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.C_Spawn"; }

 protected:
  explicit C_Spawn(::google::protobuf::Arena* arena);
  C_Spawn(::google::protobuf::Arena* arena, const C_Spawn& from);
  C_Spawn(::google::protobuf::Arena* arena, C_Spawn&& from) noexcept
      : C_Spawn(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNewLocationFieldNumber = 2,
    kNewRotationFieldNumber = 3,
    kPawnClassFieldNumber = 1,
  };
  // .GameProtocol.Location NewLocation = 2;
  bool has_newlocation() const;
  void clear_newlocation() ;
  const ::GameProtocol::Location& newlocation() const;
  PROTOBUF_NODISCARD ::GameProtocol::Location* release_newlocation();
  ::GameProtocol::Location* mutable_newlocation();
  void set_allocated_newlocation(::GameProtocol::Location* value);
  void unsafe_arena_set_allocated_newlocation(::GameProtocol::Location* value);
  ::GameProtocol::Location* unsafe_arena_release_newlocation();

  private:
  const ::GameProtocol::Location& _internal_newlocation() const;
  ::GameProtocol::Location* _internal_mutable_newlocation();

  public:
  // .GameProtocol.Rotation NewRotation = 3;
  bool has_newrotation() const;
  void clear_newrotation() ;
  const ::GameProtocol::Rotation& newrotation() const;
  PROTOBUF_NODISCARD ::GameProtocol::Rotation* release_newrotation();
  ::GameProtocol::Rotation* mutable_newrotation();
  void set_allocated_newrotation(::GameProtocol::Rotation* value);
  void unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value);
  ::GameProtocol::Rotation* unsafe_arena_release_newrotation();

  private:
  const ::GameProtocol::Rotation& _internal_newrotation() const;
  ::GameProtocol::Rotation* _internal_mutable_newrotation();

  public:
  // int32 PawnClass = 1;
  void clear_pawnclass() ;
  ::int32_t pawnclass() const;
  void set_pawnclass(::int32_t value);

  private:
  ::int32_t _internal_pawnclass() const;
  void _internal_set_pawnclass(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.C_Spawn)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const C_Spawn& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::GameProtocol::Location* newlocation_;
    ::GameProtocol::Rotation* newrotation_;
    ::int32_t pawnclass_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ActorProtocol_2eproto;
};
// -------------------------------------------------------------------

class C_Move final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.C_Move) */ {
 public:
  inline C_Move() : C_Move(nullptr) {}
  ~C_Move() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_Move* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_Move));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_Move(
      ::google::protobuf::internal::ConstantInitialized);

  inline C_Move(const C_Move& from) : C_Move(nullptr, from) {}
  inline C_Move(C_Move&& from) noexcept
      : C_Move(nullptr, std::move(from)) {}
  inline C_Move& operator=(const C_Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Move& operator=(C_Move&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_Move* internal_default_instance() {
    return reinterpret_cast<const C_Move*>(
        &_C_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(C_Move& a, C_Move& b) { a.Swap(&b); }
  inline void Swap(C_Move* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Move* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Move* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_Move>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_Move& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_Move& from) { C_Move::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_Move* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.C_Move"; }

 protected:
  explicit C_Move(::google::protobuf::Arena* arena);
  C_Move(::google::protobuf::Arena* arena, const C_Move& from);
  C_Move(::google::protobuf::Arena* arena, C_Move&& from) noexcept
      : C_Move(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNewCoordinateFieldNumber = 2,
    kNewRotationFieldNumber = 3,
    kActorIdFieldNumber = 1,
  };
  // .GameProtocol.Location NewCoordinate = 2;
  bool has_newcoordinate() const;
  void clear_newcoordinate() ;
  const ::GameProtocol::Location& newcoordinate() const;
  PROTOBUF_NODISCARD ::GameProtocol::Location* release_newcoordinate();
  ::GameProtocol::Location* mutable_newcoordinate();
  void set_allocated_newcoordinate(::GameProtocol::Location* value);
  void unsafe_arena_set_allocated_newcoordinate(::GameProtocol::Location* value);
  ::GameProtocol::Location* unsafe_arena_release_newcoordinate();

  private:
  const ::GameProtocol::Location& _internal_newcoordinate() const;
  ::GameProtocol::Location* _internal_mutable_newcoordinate();

  public:
  // .GameProtocol.Rotation NewRotation = 3;
  bool has_newrotation() const;
  void clear_newrotation() ;
  const ::GameProtocol::Rotation& newrotation() const;
  PROTOBUF_NODISCARD ::GameProtocol::Rotation* release_newrotation();
  ::GameProtocol::Rotation* mutable_newrotation();
  void set_allocated_newrotation(::GameProtocol::Rotation* value);
  void unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value);
  ::GameProtocol::Rotation* unsafe_arena_release_newrotation();

  private:
  const ::GameProtocol::Rotation& _internal_newrotation() const;
  ::GameProtocol::Rotation* _internal_mutable_newrotation();

  public:
  // int32 ActorId = 1;
  void clear_actorid() ;
  ::int32_t actorid() const;
  void set_actorid(::int32_t value);

  private:
  ::int32_t _internal_actorid() const;
  void _internal_set_actorid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.C_Move)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const C_Move& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::GameProtocol::Location* newcoordinate_;
    ::GameProtocol::Rotation* newrotation_;
    ::int32_t actorid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ActorProtocol_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// S_Spawn

// int32 PawnClass = 1;
inline void S_Spawn::clear_pawnclass() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pawnclass_ = 0;
}
inline ::int32_t S_Spawn::pawnclass() const {
  // @@protoc_insertion_point(field_get:GameProtocol.S_Spawn.PawnClass)
  return _internal_pawnclass();
}
inline void S_Spawn::set_pawnclass(::int32_t value) {
  _internal_set_pawnclass(value);
  // @@protoc_insertion_point(field_set:GameProtocol.S_Spawn.PawnClass)
}
inline ::int32_t S_Spawn::_internal_pawnclass() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pawnclass_;
}
inline void S_Spawn::_internal_set_pawnclass(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pawnclass_ = value;
}

// .GameProtocol.Location NewLocation = 2;
inline bool S_Spawn::has_newlocation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newlocation_ != nullptr);
  return value;
}
inline const ::GameProtocol::Location& S_Spawn::_internal_newlocation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Location* p = _impl_.newlocation_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Location&>(::GameProtocol::_Location_default_instance_);
}
inline const ::GameProtocol::Location& S_Spawn::newlocation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.S_Spawn.NewLocation)
  return _internal_newlocation();
}
inline void S_Spawn::unsafe_arena_set_allocated_newlocation(::GameProtocol::Location* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newlocation_);
  }
  _impl_.newlocation_ = reinterpret_cast<::GameProtocol::Location*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.S_Spawn.NewLocation)
}
inline ::GameProtocol::Location* S_Spawn::release_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* released = _impl_.newlocation_;
  _impl_.newlocation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Location* S_Spawn::unsafe_arena_release_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.S_Spawn.NewLocation)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* temp = _impl_.newlocation_;
  _impl_.newlocation_ = nullptr;
  return temp;
}
inline ::GameProtocol::Location* S_Spawn::_internal_mutable_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newlocation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Location>(GetArena());
    _impl_.newlocation_ = reinterpret_cast<::GameProtocol::Location*>(p);
  }
  return _impl_.newlocation_;
}
inline ::GameProtocol::Location* S_Spawn::mutable_newlocation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::GameProtocol::Location* _msg = _internal_mutable_newlocation();
  // @@protoc_insertion_point(field_mutable:GameProtocol.S_Spawn.NewLocation)
  return _msg;
}
inline void S_Spawn::set_allocated_newlocation(::GameProtocol::Location* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newlocation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.newlocation_ = reinterpret_cast<::GameProtocol::Location*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.S_Spawn.NewLocation)
}

// .GameProtocol.Rotation NewRotation = 3;
inline bool S_Spawn::has_newrotation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newrotation_ != nullptr);
  return value;
}
inline const ::GameProtocol::Rotation& S_Spawn::_internal_newrotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Rotation* p = _impl_.newrotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Rotation&>(::GameProtocol::_Rotation_default_instance_);
}
inline const ::GameProtocol::Rotation& S_Spawn::newrotation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.S_Spawn.NewRotation)
  return _internal_newrotation();
}
inline void S_Spawn::unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }
  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.S_Spawn.NewRotation)
}
inline ::GameProtocol::Rotation* S_Spawn::release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* released = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Rotation* S_Spawn::unsafe_arena_release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.S_Spawn.NewRotation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* temp = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  return temp;
}
inline ::GameProtocol::Rotation* S_Spawn::_internal_mutable_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Rotation>(GetArena());
    _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(p);
  }
  return _impl_.newrotation_;
}
inline ::GameProtocol::Rotation* S_Spawn::mutable_newrotation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::GameProtocol::Rotation* _msg = _internal_mutable_newrotation();
  // @@protoc_insertion_point(field_mutable:GameProtocol.S_Spawn.NewRotation)
  return _msg;
}
inline void S_Spawn::set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.S_Spawn.NewRotation)
}

// -------------------------------------------------------------------

// C_Spawn

// int32 PawnClass = 1;
inline void C_Spawn::clear_pawnclass() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pawnclass_ = 0;
}
inline ::int32_t C_Spawn::pawnclass() const {
  // @@protoc_insertion_point(field_get:GameProtocol.C_Spawn.PawnClass)
  return _internal_pawnclass();
}
inline void C_Spawn::set_pawnclass(::int32_t value) {
  _internal_set_pawnclass(value);
  // @@protoc_insertion_point(field_set:GameProtocol.C_Spawn.PawnClass)
}
inline ::int32_t C_Spawn::_internal_pawnclass() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pawnclass_;
}
inline void C_Spawn::_internal_set_pawnclass(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pawnclass_ = value;
}

// .GameProtocol.Location NewLocation = 2;
inline bool C_Spawn::has_newlocation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newlocation_ != nullptr);
  return value;
}
inline const ::GameProtocol::Location& C_Spawn::_internal_newlocation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Location* p = _impl_.newlocation_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Location&>(::GameProtocol::_Location_default_instance_);
}
inline const ::GameProtocol::Location& C_Spawn::newlocation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.C_Spawn.NewLocation)
  return _internal_newlocation();
}
inline void C_Spawn::unsafe_arena_set_allocated_newlocation(::GameProtocol::Location* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newlocation_);
  }
  _impl_.newlocation_ = reinterpret_cast<::GameProtocol::Location*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.C_Spawn.NewLocation)
}
inline ::GameProtocol::Location* C_Spawn::release_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* released = _impl_.newlocation_;
  _impl_.newlocation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Location* C_Spawn::unsafe_arena_release_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.C_Spawn.NewLocation)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* temp = _impl_.newlocation_;
  _impl_.newlocation_ = nullptr;
  return temp;
}
inline ::GameProtocol::Location* C_Spawn::_internal_mutable_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newlocation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Location>(GetArena());
    _impl_.newlocation_ = reinterpret_cast<::GameProtocol::Location*>(p);
  }
  return _impl_.newlocation_;
}
inline ::GameProtocol::Location* C_Spawn::mutable_newlocation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::GameProtocol::Location* _msg = _internal_mutable_newlocation();
  // @@protoc_insertion_point(field_mutable:GameProtocol.C_Spawn.NewLocation)
  return _msg;
}
inline void C_Spawn::set_allocated_newlocation(::GameProtocol::Location* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newlocation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.newlocation_ = reinterpret_cast<::GameProtocol::Location*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.C_Spawn.NewLocation)
}

// .GameProtocol.Rotation NewRotation = 3;
inline bool C_Spawn::has_newrotation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newrotation_ != nullptr);
  return value;
}
inline const ::GameProtocol::Rotation& C_Spawn::_internal_newrotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Rotation* p = _impl_.newrotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Rotation&>(::GameProtocol::_Rotation_default_instance_);
}
inline const ::GameProtocol::Rotation& C_Spawn::newrotation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.C_Spawn.NewRotation)
  return _internal_newrotation();
}
inline void C_Spawn::unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }
  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.C_Spawn.NewRotation)
}
inline ::GameProtocol::Rotation* C_Spawn::release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* released = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Rotation* C_Spawn::unsafe_arena_release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.C_Spawn.NewRotation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* temp = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  return temp;
}
inline ::GameProtocol::Rotation* C_Spawn::_internal_mutable_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Rotation>(GetArena());
    _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(p);
  }
  return _impl_.newrotation_;
}
inline ::GameProtocol::Rotation* C_Spawn::mutable_newrotation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::GameProtocol::Rotation* _msg = _internal_mutable_newrotation();
  // @@protoc_insertion_point(field_mutable:GameProtocol.C_Spawn.NewRotation)
  return _msg;
}
inline void C_Spawn::set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.C_Spawn.NewRotation)
}

// -------------------------------------------------------------------

// S_Move

// int32 ActorId = 1;
inline void S_Move::clear_actorid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.actorid_ = 0;
}
inline ::int32_t S_Move::actorid() const {
  // @@protoc_insertion_point(field_get:GameProtocol.S_Move.ActorId)
  return _internal_actorid();
}
inline void S_Move::set_actorid(::int32_t value) {
  _internal_set_actorid(value);
  // @@protoc_insertion_point(field_set:GameProtocol.S_Move.ActorId)
}
inline ::int32_t S_Move::_internal_actorid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.actorid_;
}
inline void S_Move::_internal_set_actorid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.actorid_ = value;
}

// .GameProtocol.Location NewCoordinate = 2;
inline bool S_Move::has_newcoordinate() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newcoordinate_ != nullptr);
  return value;
}
inline const ::GameProtocol::Location& S_Move::_internal_newcoordinate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Location* p = _impl_.newcoordinate_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Location&>(::GameProtocol::_Location_default_instance_);
}
inline const ::GameProtocol::Location& S_Move::newcoordinate() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.S_Move.NewCoordinate)
  return _internal_newcoordinate();
}
inline void S_Move::unsafe_arena_set_allocated_newcoordinate(::GameProtocol::Location* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newcoordinate_);
  }
  _impl_.newcoordinate_ = reinterpret_cast<::GameProtocol::Location*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.S_Move.NewCoordinate)
}
inline ::GameProtocol::Location* S_Move::release_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* released = _impl_.newcoordinate_;
  _impl_.newcoordinate_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Location* S_Move::unsafe_arena_release_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.S_Move.NewCoordinate)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* temp = _impl_.newcoordinate_;
  _impl_.newcoordinate_ = nullptr;
  return temp;
}
inline ::GameProtocol::Location* S_Move::_internal_mutable_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newcoordinate_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Location>(GetArena());
    _impl_.newcoordinate_ = reinterpret_cast<::GameProtocol::Location*>(p);
  }
  return _impl_.newcoordinate_;
}
inline ::GameProtocol::Location* S_Move::mutable_newcoordinate() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::GameProtocol::Location* _msg = _internal_mutable_newcoordinate();
  // @@protoc_insertion_point(field_mutable:GameProtocol.S_Move.NewCoordinate)
  return _msg;
}
inline void S_Move::set_allocated_newcoordinate(::GameProtocol::Location* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newcoordinate_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.newcoordinate_ = reinterpret_cast<::GameProtocol::Location*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.S_Move.NewCoordinate)
}

// .GameProtocol.Rotation NewRotation = 3;
inline bool S_Move::has_newrotation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newrotation_ != nullptr);
  return value;
}
inline const ::GameProtocol::Rotation& S_Move::_internal_newrotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Rotation* p = _impl_.newrotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Rotation&>(::GameProtocol::_Rotation_default_instance_);
}
inline const ::GameProtocol::Rotation& S_Move::newrotation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.S_Move.NewRotation)
  return _internal_newrotation();
}
inline void S_Move::unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }
  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.S_Move.NewRotation)
}
inline ::GameProtocol::Rotation* S_Move::release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* released = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Rotation* S_Move::unsafe_arena_release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.S_Move.NewRotation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* temp = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  return temp;
}
inline ::GameProtocol::Rotation* S_Move::_internal_mutable_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Rotation>(GetArena());
    _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(p);
  }
  return _impl_.newrotation_;
}
inline ::GameProtocol::Rotation* S_Move::mutable_newrotation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::GameProtocol::Rotation* _msg = _internal_mutable_newrotation();
  // @@protoc_insertion_point(field_mutable:GameProtocol.S_Move.NewRotation)
  return _msg;
}
inline void S_Move::set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.S_Move.NewRotation)
}

// -------------------------------------------------------------------

// C_Move

// int32 ActorId = 1;
inline void C_Move::clear_actorid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.actorid_ = 0;
}
inline ::int32_t C_Move::actorid() const {
  // @@protoc_insertion_point(field_get:GameProtocol.C_Move.ActorId)
  return _internal_actorid();
}
inline void C_Move::set_actorid(::int32_t value) {
  _internal_set_actorid(value);
  // @@protoc_insertion_point(field_set:GameProtocol.C_Move.ActorId)
}
inline ::int32_t C_Move::_internal_actorid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.actorid_;
}
inline void C_Move::_internal_set_actorid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.actorid_ = value;
}

// .GameProtocol.Location NewCoordinate = 2;
inline bool C_Move::has_newcoordinate() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newcoordinate_ != nullptr);
  return value;
}
inline const ::GameProtocol::Location& C_Move::_internal_newcoordinate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Location* p = _impl_.newcoordinate_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Location&>(::GameProtocol::_Location_default_instance_);
}
inline const ::GameProtocol::Location& C_Move::newcoordinate() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.C_Move.NewCoordinate)
  return _internal_newcoordinate();
}
inline void C_Move::unsafe_arena_set_allocated_newcoordinate(::GameProtocol::Location* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newcoordinate_);
  }
  _impl_.newcoordinate_ = reinterpret_cast<::GameProtocol::Location*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.C_Move.NewCoordinate)
}
inline ::GameProtocol::Location* C_Move::release_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* released = _impl_.newcoordinate_;
  _impl_.newcoordinate_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Location* C_Move::unsafe_arena_release_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.C_Move.NewCoordinate)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Location* temp = _impl_.newcoordinate_;
  _impl_.newcoordinate_ = nullptr;
  return temp;
}
inline ::GameProtocol::Location* C_Move::_internal_mutable_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newcoordinate_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Location>(GetArena());
    _impl_.newcoordinate_ = reinterpret_cast<::GameProtocol::Location*>(p);
  }
  return _impl_.newcoordinate_;
}
inline ::GameProtocol::Location* C_Move::mutable_newcoordinate() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::GameProtocol::Location* _msg = _internal_mutable_newcoordinate();
  // @@protoc_insertion_point(field_mutable:GameProtocol.C_Move.NewCoordinate)
  return _msg;
}
inline void C_Move::set_allocated_newcoordinate(::GameProtocol::Location* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newcoordinate_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.newcoordinate_ = reinterpret_cast<::GameProtocol::Location*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.C_Move.NewCoordinate)
}

// .GameProtocol.Rotation NewRotation = 3;
inline bool C_Move::has_newrotation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.newrotation_ != nullptr);
  return value;
}
inline const ::GameProtocol::Rotation& C_Move::_internal_newrotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Rotation* p = _impl_.newrotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Rotation&>(::GameProtocol::_Rotation_default_instance_);
}
inline const ::GameProtocol::Rotation& C_Move::newrotation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.C_Move.NewRotation)
  return _internal_newrotation();
}
inline void C_Move::unsafe_arena_set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }
  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.C_Move.NewRotation)
}
inline ::GameProtocol::Rotation* C_Move::release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* released = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Rotation* C_Move::unsafe_arena_release_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.C_Move.NewRotation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::GameProtocol::Rotation* temp = _impl_.newrotation_;
  _impl_.newrotation_ = nullptr;
  return temp;
}
inline ::GameProtocol::Rotation* C_Move::_internal_mutable_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Rotation>(GetArena());
    _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(p);
  }
  return _impl_.newrotation_;
}
inline ::GameProtocol::Rotation* C_Move::mutable_newrotation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::GameProtocol::Rotation* _msg = _internal_mutable_newrotation();
  // @@protoc_insertion_point(field_mutable:GameProtocol.C_Move.NewRotation)
  return _msg;
}
inline void C_Move::set_allocated_newrotation(::GameProtocol::Rotation* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.newrotation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.newrotation_ = reinterpret_cast<::GameProtocol::Rotation*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.C_Move.NewRotation)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GameProtocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ActorProtocol_2eproto_2epb_2eh
