// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ActorProtocol.proto
// Protobuf C++ Version: 5.29.3

#include "ActorProtocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GameProtocol {

inline constexpr S_Spawn::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        newlocation_{nullptr},
        newrotation_{nullptr},
        pawnclass_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_Spawn::S_Spawn(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_SpawnDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_SpawnDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_SpawnDefaultTypeInternal() {}
  union {
    S_Spawn _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_SpawnDefaultTypeInternal _S_Spawn_default_instance_;

inline constexpr S_Move::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        newcoordinate_{nullptr},
        newrotation_{nullptr},
        actorid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S_Move::S_Move(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S_MoveDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_MoveDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_MoveDefaultTypeInternal() {}
  union {
    S_Move _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_MoveDefaultTypeInternal _S_Move_default_instance_;

inline constexpr C_Spawn::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        newlocation_{nullptr},
        newrotation_{nullptr},
        pawnclass_{0} {}

template <typename>
PROTOBUF_CONSTEXPR C_Spawn::C_Spawn(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C_SpawnDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_SpawnDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_SpawnDefaultTypeInternal() {}
  union {
    C_Spawn _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_SpawnDefaultTypeInternal _C_Spawn_default_instance_;

inline constexpr C_Move::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        newcoordinate_{nullptr},
        newrotation_{nullptr},
        actorid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR C_Move::C_Move(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C_MoveDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_MoveDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_MoveDefaultTypeInternal() {}
  union {
    C_Move _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_MoveDefaultTypeInternal _C_Move_default_instance_;
}  // namespace GameProtocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ActorProtocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ActorProtocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_ActorProtocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Spawn, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Spawn, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Spawn, _impl_.pawnclass_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Spawn, _impl_.newlocation_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Spawn, _impl_.newrotation_),
        ~0u,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Spawn, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Spawn, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Spawn, _impl_.pawnclass_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Spawn, _impl_.newlocation_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Spawn, _impl_.newrotation_),
        ~0u,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Move, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Move, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Move, _impl_.actorid_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Move, _impl_.newcoordinate_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::S_Move, _impl_.newrotation_),
        ~0u,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Move, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Move, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Move, _impl_.actorid_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Move, _impl_.newcoordinate_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::C_Move, _impl_.newrotation_),
        ~0u,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::GameProtocol::S_Spawn)},
        {14, 25, -1, sizeof(::GameProtocol::C_Spawn)},
        {28, 39, -1, sizeof(::GameProtocol::S_Move)},
        {42, 53, -1, sizeof(::GameProtocol::C_Move)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::GameProtocol::_S_Spawn_default_instance_._instance,
    &::GameProtocol::_C_Spawn_default_instance_._instance,
    &::GameProtocol::_S_Move_default_instance_._instance,
    &::GameProtocol::_C_Move_default_instance_._instance,
};
const char descriptor_table_protodef_ActorProtocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023ActorProtocol.proto\022\014GameProtocol\032\014Str"
    "uct.proto\"v\n\007S_Spawn\022\021\n\tPawnClass\030\001 \001(\005\022"
    "+\n\013NewLocation\030\002 \001(\0132\026.GameProtocol.Loca"
    "tion\022+\n\013NewRotation\030\003 \001(\0132\026.GameProtocol"
    ".Rotation\"v\n\007C_Spawn\022\021\n\tPawnClass\030\001 \001(\005\022"
    "+\n\013NewLocation\030\002 \001(\0132\026.GameProtocol.Loca"
    "tion\022+\n\013NewRotation\030\003 \001(\0132\026.GameProtocol"
    ".Rotation\"u\n\006S_Move\022\017\n\007ActorId\030\001 \001(\005\022-\n\r"
    "NewCoordinate\030\002 \001(\0132\026.GameProtocol.Locat"
    "ion\022+\n\013NewRotation\030\003 \001(\0132\026.GameProtocol."
    "Rotation\"u\n\006C_Move\022\017\n\007ActorId\030\001 \001(\005\022-\n\rN"
    "ewCoordinate\030\002 \001(\0132\026.GameProtocol.Locati"
    "on\022+\n\013NewRotation\030\003 \001(\0132\026.GameProtocol.R"
    "otationb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_ActorProtocol_2eproto_deps[1] =
    {
        &::descriptor_table_Struct_2eproto,
};
static ::absl::once_flag descriptor_table_ActorProtocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ActorProtocol_2eproto = {
    false,
    false,
    535,
    descriptor_table_protodef_ActorProtocol_2eproto,
    "ActorProtocol.proto",
    &descriptor_table_ActorProtocol_2eproto_once,
    descriptor_table_ActorProtocol_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_ActorProtocol_2eproto::offsets,
    file_level_enum_descriptors_ActorProtocol_2eproto,
    file_level_service_descriptors_ActorProtocol_2eproto,
};
namespace GameProtocol {
// ===================================================================

class S_Spawn::_Internal {
 public:
  using HasBits =
      decltype(std::declval<S_Spawn>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_._has_bits_);
};

void S_Spawn::clear_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newlocation_ != nullptr) _impl_.newlocation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void S_Spawn::clear_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ != nullptr) _impl_.newrotation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
S_Spawn::S_Spawn(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.S_Spawn)
}
inline PROTOBUF_NDEBUG_INLINE S_Spawn::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::S_Spawn& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

S_Spawn::S_Spawn(
    ::google::protobuf::Arena* arena,
    const S_Spawn& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S_Spawn* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.newlocation_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(
                              arena, *from._impl_.newlocation_)
                        : nullptr;
  _impl_.newrotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(
                              arena, *from._impl_.newrotation_)
                        : nullptr;
  _impl_.pawnclass_ = from._impl_.pawnclass_;

  // @@protoc_insertion_point(copy_constructor:GameProtocol.S_Spawn)
}
inline PROTOBUF_NDEBUG_INLINE S_Spawn::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void S_Spawn::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, newlocation_),
           0,
           offsetof(Impl_, pawnclass_) -
               offsetof(Impl_, newlocation_) +
               sizeof(Impl_::pawnclass_));
}
S_Spawn::~S_Spawn() {
  // @@protoc_insertion_point(destructor:GameProtocol.S_Spawn)
  SharedDtor(*this);
}
inline void S_Spawn::SharedDtor(MessageLite& self) {
  S_Spawn& this_ = static_cast<S_Spawn&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.newlocation_;
  delete this_._impl_.newrotation_;
  this_._impl_.~Impl_();
}

inline void* S_Spawn::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_Spawn(arena);
}
constexpr auto S_Spawn::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S_Spawn),
                                            alignof(S_Spawn));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_Spawn::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_Spawn_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_Spawn::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_Spawn>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_Spawn::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_Spawn>(), &S_Spawn::ByteSizeLong,
            &S_Spawn::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_._cached_size_),
        false,
    },
    &S_Spawn::kDescriptorMethods,
    &descriptor_table_ActorProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_Spawn::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> S_Spawn::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::S_Spawn>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 PawnClass = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S_Spawn, _impl_.pawnclass_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.pawnclass_)}},
    // .GameProtocol.Location NewLocation = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.newlocation_)}},
    // .GameProtocol.Rotation NewRotation = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.newrotation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 PawnClass = 1;
    {PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.pawnclass_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .GameProtocol.Location NewLocation = 2;
    {PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.newlocation_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .GameProtocol.Rotation NewRotation = 3;
    {PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.newrotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GameProtocol::Location>()},
    {::_pbi::TcParser::GetTable<::GameProtocol::Rotation>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void S_Spawn::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.S_Spawn)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.newlocation_ != nullptr);
      _impl_.newlocation_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.newrotation_ != nullptr);
      _impl_.newrotation_->Clear();
    }
  }
  _impl_.pawnclass_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_Spawn::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_Spawn& this_ = static_cast<const S_Spawn&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_Spawn::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_Spawn& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.S_Spawn)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 PawnClass = 1;
          if (this_._internal_pawnclass() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_pawnclass(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .GameProtocol.Location NewLocation = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.newlocation_, this_._impl_.newlocation_->GetCachedSize(), target,
                stream);
          }

          // .GameProtocol.Rotation NewRotation = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.newrotation_, this_._impl_.newrotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.S_Spawn)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_Spawn::ByteSizeLong(const MessageLite& base) {
          const S_Spawn& this_ = static_cast<const S_Spawn&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_Spawn::ByteSizeLong() const {
          const S_Spawn& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.S_Spawn)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .GameProtocol.Location NewLocation = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newlocation_);
            }
            // .GameProtocol.Rotation NewRotation = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newrotation_);
            }
          }
           {
            // int32 PawnClass = 1;
            if (this_._internal_pawnclass() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_pawnclass());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_Spawn::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_Spawn*>(&to_msg);
  auto& from = static_cast<const S_Spawn&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.S_Spawn)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.newlocation_ != nullptr);
      if (_this->_impl_.newlocation_ == nullptr) {
        _this->_impl_.newlocation_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(arena, *from._impl_.newlocation_);
      } else {
        _this->_impl_.newlocation_->MergeFrom(*from._impl_.newlocation_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.newrotation_ != nullptr);
      if (_this->_impl_.newrotation_ == nullptr) {
        _this->_impl_.newrotation_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(arena, *from._impl_.newrotation_);
      } else {
        _this->_impl_.newrotation_->MergeFrom(*from._impl_.newrotation_);
      }
    }
  }
  if (from._internal_pawnclass() != 0) {
    _this->_impl_.pawnclass_ = from._impl_.pawnclass_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_Spawn::CopyFrom(const S_Spawn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.S_Spawn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_Spawn::InternalSwap(S_Spawn* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.pawnclass_)
      + sizeof(S_Spawn::_impl_.pawnclass_)
      - PROTOBUF_FIELD_OFFSET(S_Spawn, _impl_.newlocation_)>(
          reinterpret_cast<char*>(&_impl_.newlocation_),
          reinterpret_cast<char*>(&other->_impl_.newlocation_));
}

::google::protobuf::Metadata S_Spawn::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class C_Spawn::_Internal {
 public:
  using HasBits =
      decltype(std::declval<C_Spawn>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_._has_bits_);
};

void C_Spawn::clear_newlocation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newlocation_ != nullptr) _impl_.newlocation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void C_Spawn::clear_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ != nullptr) _impl_.newrotation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
C_Spawn::C_Spawn(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.C_Spawn)
}
inline PROTOBUF_NDEBUG_INLINE C_Spawn::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::C_Spawn& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

C_Spawn::C_Spawn(
    ::google::protobuf::Arena* arena,
    const C_Spawn& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  C_Spawn* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.newlocation_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(
                              arena, *from._impl_.newlocation_)
                        : nullptr;
  _impl_.newrotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(
                              arena, *from._impl_.newrotation_)
                        : nullptr;
  _impl_.pawnclass_ = from._impl_.pawnclass_;

  // @@protoc_insertion_point(copy_constructor:GameProtocol.C_Spawn)
}
inline PROTOBUF_NDEBUG_INLINE C_Spawn::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void C_Spawn::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, newlocation_),
           0,
           offsetof(Impl_, pawnclass_) -
               offsetof(Impl_, newlocation_) +
               sizeof(Impl_::pawnclass_));
}
C_Spawn::~C_Spawn() {
  // @@protoc_insertion_point(destructor:GameProtocol.C_Spawn)
  SharedDtor(*this);
}
inline void C_Spawn::SharedDtor(MessageLite& self) {
  C_Spawn& this_ = static_cast<C_Spawn&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.newlocation_;
  delete this_._impl_.newrotation_;
  this_._impl_.~Impl_();
}

inline void* C_Spawn::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) C_Spawn(arena);
}
constexpr auto C_Spawn::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(C_Spawn),
                                            alignof(C_Spawn));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull C_Spawn::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_C_Spawn_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &C_Spawn::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<C_Spawn>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &C_Spawn::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<C_Spawn>(), &C_Spawn::ByteSizeLong,
            &C_Spawn::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_._cached_size_),
        false,
    },
    &C_Spawn::kDescriptorMethods,
    &descriptor_table_ActorProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* C_Spawn::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> C_Spawn::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::C_Spawn>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 PawnClass = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(C_Spawn, _impl_.pawnclass_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.pawnclass_)}},
    // .GameProtocol.Location NewLocation = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.newlocation_)}},
    // .GameProtocol.Rotation NewRotation = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.newrotation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 PawnClass = 1;
    {PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.pawnclass_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .GameProtocol.Location NewLocation = 2;
    {PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.newlocation_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .GameProtocol.Rotation NewRotation = 3;
    {PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.newrotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GameProtocol::Location>()},
    {::_pbi::TcParser::GetTable<::GameProtocol::Rotation>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void C_Spawn::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.C_Spawn)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.newlocation_ != nullptr);
      _impl_.newlocation_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.newrotation_ != nullptr);
      _impl_.newrotation_->Clear();
    }
  }
  _impl_.pawnclass_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* C_Spawn::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const C_Spawn& this_ = static_cast<const C_Spawn&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* C_Spawn::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const C_Spawn& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.C_Spawn)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 PawnClass = 1;
          if (this_._internal_pawnclass() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_pawnclass(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .GameProtocol.Location NewLocation = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.newlocation_, this_._impl_.newlocation_->GetCachedSize(), target,
                stream);
          }

          // .GameProtocol.Rotation NewRotation = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.newrotation_, this_._impl_.newrotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.C_Spawn)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t C_Spawn::ByteSizeLong(const MessageLite& base) {
          const C_Spawn& this_ = static_cast<const C_Spawn&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t C_Spawn::ByteSizeLong() const {
          const C_Spawn& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.C_Spawn)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .GameProtocol.Location NewLocation = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newlocation_);
            }
            // .GameProtocol.Rotation NewRotation = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newrotation_);
            }
          }
           {
            // int32 PawnClass = 1;
            if (this_._internal_pawnclass() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_pawnclass());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void C_Spawn::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<C_Spawn*>(&to_msg);
  auto& from = static_cast<const C_Spawn&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.C_Spawn)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.newlocation_ != nullptr);
      if (_this->_impl_.newlocation_ == nullptr) {
        _this->_impl_.newlocation_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(arena, *from._impl_.newlocation_);
      } else {
        _this->_impl_.newlocation_->MergeFrom(*from._impl_.newlocation_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.newrotation_ != nullptr);
      if (_this->_impl_.newrotation_ == nullptr) {
        _this->_impl_.newrotation_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(arena, *from._impl_.newrotation_);
      } else {
        _this->_impl_.newrotation_->MergeFrom(*from._impl_.newrotation_);
      }
    }
  }
  if (from._internal_pawnclass() != 0) {
    _this->_impl_.pawnclass_ = from._impl_.pawnclass_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void C_Spawn::CopyFrom(const C_Spawn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.C_Spawn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C_Spawn::InternalSwap(C_Spawn* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.pawnclass_)
      + sizeof(C_Spawn::_impl_.pawnclass_)
      - PROTOBUF_FIELD_OFFSET(C_Spawn, _impl_.newlocation_)>(
          reinterpret_cast<char*>(&_impl_.newlocation_),
          reinterpret_cast<char*>(&other->_impl_.newlocation_));
}

::google::protobuf::Metadata C_Spawn::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S_Move::_Internal {
 public:
  using HasBits =
      decltype(std::declval<S_Move>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(S_Move, _impl_._has_bits_);
};

void S_Move::clear_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newcoordinate_ != nullptr) _impl_.newcoordinate_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void S_Move::clear_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ != nullptr) _impl_.newrotation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
S_Move::S_Move(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.S_Move)
}
inline PROTOBUF_NDEBUG_INLINE S_Move::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::S_Move& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

S_Move::S_Move(
    ::google::protobuf::Arena* arena,
    const S_Move& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S_Move* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.newcoordinate_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(
                              arena, *from._impl_.newcoordinate_)
                        : nullptr;
  _impl_.newrotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(
                              arena, *from._impl_.newrotation_)
                        : nullptr;
  _impl_.actorid_ = from._impl_.actorid_;

  // @@protoc_insertion_point(copy_constructor:GameProtocol.S_Move)
}
inline PROTOBUF_NDEBUG_INLINE S_Move::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void S_Move::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, newcoordinate_),
           0,
           offsetof(Impl_, actorid_) -
               offsetof(Impl_, newcoordinate_) +
               sizeof(Impl_::actorid_));
}
S_Move::~S_Move() {
  // @@protoc_insertion_point(destructor:GameProtocol.S_Move)
  SharedDtor(*this);
}
inline void S_Move::SharedDtor(MessageLite& self) {
  S_Move& this_ = static_cast<S_Move&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.newcoordinate_;
  delete this_._impl_.newrotation_;
  this_._impl_.~Impl_();
}

inline void* S_Move::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S_Move(arena);
}
constexpr auto S_Move::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S_Move),
                                            alignof(S_Move));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S_Move::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S_Move_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S_Move::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S_Move>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S_Move::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S_Move>(), &S_Move::ByteSizeLong,
            &S_Move::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S_Move, _impl_._cached_size_),
        false,
    },
    &S_Move::kDescriptorMethods,
    &descriptor_table_ActorProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S_Move::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> S_Move::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(S_Move, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::S_Move>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 ActorId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S_Move, _impl_.actorid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S_Move, _impl_.actorid_)}},
    // .GameProtocol.Location NewCoordinate = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(S_Move, _impl_.newcoordinate_)}},
    // .GameProtocol.Rotation NewRotation = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(S_Move, _impl_.newrotation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ActorId = 1;
    {PROTOBUF_FIELD_OFFSET(S_Move, _impl_.actorid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .GameProtocol.Location NewCoordinate = 2;
    {PROTOBUF_FIELD_OFFSET(S_Move, _impl_.newcoordinate_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .GameProtocol.Rotation NewRotation = 3;
    {PROTOBUF_FIELD_OFFSET(S_Move, _impl_.newrotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GameProtocol::Location>()},
    {::_pbi::TcParser::GetTable<::GameProtocol::Rotation>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void S_Move::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.S_Move)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.newcoordinate_ != nullptr);
      _impl_.newcoordinate_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.newrotation_ != nullptr);
      _impl_.newrotation_->Clear();
    }
  }
  _impl_.actorid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S_Move::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S_Move& this_ = static_cast<const S_Move&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S_Move::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S_Move& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.S_Move)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 ActorId = 1;
          if (this_._internal_actorid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_actorid(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .GameProtocol.Location NewCoordinate = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.newcoordinate_, this_._impl_.newcoordinate_->GetCachedSize(), target,
                stream);
          }

          // .GameProtocol.Rotation NewRotation = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.newrotation_, this_._impl_.newrotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.S_Move)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S_Move::ByteSizeLong(const MessageLite& base) {
          const S_Move& this_ = static_cast<const S_Move&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S_Move::ByteSizeLong() const {
          const S_Move& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.S_Move)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .GameProtocol.Location NewCoordinate = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newcoordinate_);
            }
            // .GameProtocol.Rotation NewRotation = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newrotation_);
            }
          }
           {
            // int32 ActorId = 1;
            if (this_._internal_actorid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_actorid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S_Move::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S_Move*>(&to_msg);
  auto& from = static_cast<const S_Move&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.S_Move)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.newcoordinate_ != nullptr);
      if (_this->_impl_.newcoordinate_ == nullptr) {
        _this->_impl_.newcoordinate_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(arena, *from._impl_.newcoordinate_);
      } else {
        _this->_impl_.newcoordinate_->MergeFrom(*from._impl_.newcoordinate_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.newrotation_ != nullptr);
      if (_this->_impl_.newrotation_ == nullptr) {
        _this->_impl_.newrotation_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(arena, *from._impl_.newrotation_);
      } else {
        _this->_impl_.newrotation_->MergeFrom(*from._impl_.newrotation_);
      }
    }
  }
  if (from._internal_actorid() != 0) {
    _this->_impl_.actorid_ = from._impl_.actorid_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S_Move::CopyFrom(const S_Move& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.S_Move)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S_Move::InternalSwap(S_Move* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S_Move, _impl_.actorid_)
      + sizeof(S_Move::_impl_.actorid_)
      - PROTOBUF_FIELD_OFFSET(S_Move, _impl_.newcoordinate_)>(
          reinterpret_cast<char*>(&_impl_.newcoordinate_),
          reinterpret_cast<char*>(&other->_impl_.newcoordinate_));
}

::google::protobuf::Metadata S_Move::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class C_Move::_Internal {
 public:
  using HasBits =
      decltype(std::declval<C_Move>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(C_Move, _impl_._has_bits_);
};

void C_Move::clear_newcoordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newcoordinate_ != nullptr) _impl_.newcoordinate_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void C_Move::clear_newrotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.newrotation_ != nullptr) _impl_.newrotation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
C_Move::C_Move(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.C_Move)
}
inline PROTOBUF_NDEBUG_INLINE C_Move::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::C_Move& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

C_Move::C_Move(
    ::google::protobuf::Arena* arena,
    const C_Move& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  C_Move* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.newcoordinate_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(
                              arena, *from._impl_.newcoordinate_)
                        : nullptr;
  _impl_.newrotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(
                              arena, *from._impl_.newrotation_)
                        : nullptr;
  _impl_.actorid_ = from._impl_.actorid_;

  // @@protoc_insertion_point(copy_constructor:GameProtocol.C_Move)
}
inline PROTOBUF_NDEBUG_INLINE C_Move::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void C_Move::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, newcoordinate_),
           0,
           offsetof(Impl_, actorid_) -
               offsetof(Impl_, newcoordinate_) +
               sizeof(Impl_::actorid_));
}
C_Move::~C_Move() {
  // @@protoc_insertion_point(destructor:GameProtocol.C_Move)
  SharedDtor(*this);
}
inline void C_Move::SharedDtor(MessageLite& self) {
  C_Move& this_ = static_cast<C_Move&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.newcoordinate_;
  delete this_._impl_.newrotation_;
  this_._impl_.~Impl_();
}

inline void* C_Move::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) C_Move(arena);
}
constexpr auto C_Move::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(C_Move),
                                            alignof(C_Move));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull C_Move::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_C_Move_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &C_Move::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<C_Move>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &C_Move::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<C_Move>(), &C_Move::ByteSizeLong,
            &C_Move::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(C_Move, _impl_._cached_size_),
        false,
    },
    &C_Move::kDescriptorMethods,
    &descriptor_table_ActorProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* C_Move::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> C_Move::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(C_Move, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::C_Move>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 ActorId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(C_Move, _impl_.actorid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(C_Move, _impl_.actorid_)}},
    // .GameProtocol.Location NewCoordinate = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(C_Move, _impl_.newcoordinate_)}},
    // .GameProtocol.Rotation NewRotation = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(C_Move, _impl_.newrotation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ActorId = 1;
    {PROTOBUF_FIELD_OFFSET(C_Move, _impl_.actorid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .GameProtocol.Location NewCoordinate = 2;
    {PROTOBUF_FIELD_OFFSET(C_Move, _impl_.newcoordinate_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .GameProtocol.Rotation NewRotation = 3;
    {PROTOBUF_FIELD_OFFSET(C_Move, _impl_.newrotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GameProtocol::Location>()},
    {::_pbi::TcParser::GetTable<::GameProtocol::Rotation>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void C_Move::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.C_Move)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.newcoordinate_ != nullptr);
      _impl_.newcoordinate_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.newrotation_ != nullptr);
      _impl_.newrotation_->Clear();
    }
  }
  _impl_.actorid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* C_Move::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const C_Move& this_ = static_cast<const C_Move&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* C_Move::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const C_Move& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.C_Move)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 ActorId = 1;
          if (this_._internal_actorid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_actorid(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .GameProtocol.Location NewCoordinate = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.newcoordinate_, this_._impl_.newcoordinate_->GetCachedSize(), target,
                stream);
          }

          // .GameProtocol.Rotation NewRotation = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.newrotation_, this_._impl_.newrotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.C_Move)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t C_Move::ByteSizeLong(const MessageLite& base) {
          const C_Move& this_ = static_cast<const C_Move&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t C_Move::ByteSizeLong() const {
          const C_Move& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.C_Move)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .GameProtocol.Location NewCoordinate = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newcoordinate_);
            }
            // .GameProtocol.Rotation NewRotation = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.newrotation_);
            }
          }
           {
            // int32 ActorId = 1;
            if (this_._internal_actorid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_actorid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void C_Move::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<C_Move*>(&to_msg);
  auto& from = static_cast<const C_Move&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.C_Move)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.newcoordinate_ != nullptr);
      if (_this->_impl_.newcoordinate_ == nullptr) {
        _this->_impl_.newcoordinate_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Location>(arena, *from._impl_.newcoordinate_);
      } else {
        _this->_impl_.newcoordinate_->MergeFrom(*from._impl_.newcoordinate_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.newrotation_ != nullptr);
      if (_this->_impl_.newrotation_ == nullptr) {
        _this->_impl_.newrotation_ =
            ::google::protobuf::Message::CopyConstruct<::GameProtocol::Rotation>(arena, *from._impl_.newrotation_);
      } else {
        _this->_impl_.newrotation_->MergeFrom(*from._impl_.newrotation_);
      }
    }
  }
  if (from._internal_actorid() != 0) {
    _this->_impl_.actorid_ = from._impl_.actorid_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void C_Move::CopyFrom(const C_Move& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.C_Move)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C_Move::InternalSwap(C_Move* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_Move, _impl_.actorid_)
      + sizeof(C_Move::_impl_.actorid_)
      - PROTOBUF_FIELD_OFFSET(C_Move, _impl_.newcoordinate_)>(
          reinterpret_cast<char*>(&_impl_.newcoordinate_),
          reinterpret_cast<char*>(&other->_impl_.newcoordinate_));
}

::google::protobuf::Metadata C_Move::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GameProtocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ActorProtocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
