// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ControlProtocol.proto
// Protobuf C++ Version: 5.29.3

#ifndef ControlProtocol_2eproto_2epb_2eh
#define ControlProtocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ControlProtocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ControlProtocol_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ControlProtocol_2eproto;
namespace GameProtocol {
class NMT_Challenge;
struct NMT_ChallengeDefaultTypeInternal;
extern NMT_ChallengeDefaultTypeInternal _NMT_Challenge_default_instance_;
class NMT_Failure;
struct NMT_FailureDefaultTypeInternal;
extern NMT_FailureDefaultTypeInternal _NMT_Failure_default_instance_;
class NMT_Hello;
struct NMT_HelloDefaultTypeInternal;
extern NMT_HelloDefaultTypeInternal _NMT_Hello_default_instance_;
class NMT_Join;
struct NMT_JoinDefaultTypeInternal;
extern NMT_JoinDefaultTypeInternal _NMT_Join_default_instance_;
class NMT_Login;
struct NMT_LoginDefaultTypeInternal;
extern NMT_LoginDefaultTypeInternal _NMT_Login_default_instance_;
class NMT_NetSpeed;
struct NMT_NetSpeedDefaultTypeInternal;
extern NMT_NetSpeedDefaultTypeInternal _NMT_NetSpeed_default_instance_;
class NMT_Welcome;
struct NMT_WelcomeDefaultTypeInternal;
extern NMT_WelcomeDefaultTypeInternal _NMT_Welcome_default_instance_;
}  // namespace GameProtocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace GameProtocol {

// ===================================================================


// -------------------------------------------------------------------

class NMT_NetSpeed final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.NMT_NetSpeed) */ {
 public:
  inline NMT_NetSpeed() : NMT_NetSpeed(nullptr) {}
  ~NMT_NetSpeed() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NMT_NetSpeed* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NMT_NetSpeed));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NMT_NetSpeed(
      ::google::protobuf::internal::ConstantInitialized);

  inline NMT_NetSpeed(const NMT_NetSpeed& from) : NMT_NetSpeed(nullptr, from) {}
  inline NMT_NetSpeed(NMT_NetSpeed&& from) noexcept
      : NMT_NetSpeed(nullptr, std::move(from)) {}
  inline NMT_NetSpeed& operator=(const NMT_NetSpeed& from) {
    CopyFrom(from);
    return *this;
  }
  inline NMT_NetSpeed& operator=(NMT_NetSpeed&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NMT_NetSpeed& default_instance() {
    return *internal_default_instance();
  }
  static inline const NMT_NetSpeed* internal_default_instance() {
    return reinterpret_cast<const NMT_NetSpeed*>(
        &_NMT_NetSpeed_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(NMT_NetSpeed& a, NMT_NetSpeed& b) { a.Swap(&b); }
  inline void Swap(NMT_NetSpeed* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NMT_NetSpeed* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NMT_NetSpeed* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NMT_NetSpeed>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NMT_NetSpeed& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NMT_NetSpeed& from) { NMT_NetSpeed::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NMT_NetSpeed* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.NMT_NetSpeed"; }

 protected:
  explicit NMT_NetSpeed(::google::protobuf::Arena* arena);
  NMT_NetSpeed(::google::protobuf::Arena* arena, const NMT_NetSpeed& from);
  NMT_NetSpeed(::google::protobuf::Arena* arena, NMT_NetSpeed&& from) noexcept
      : NMT_NetSpeed(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLastAckedPacketTimeFieldNumber = 1,
  };
  // uint64 LastAckedPacketTime = 1;
  void clear_lastackedpackettime() ;
  ::uint64_t lastackedpackettime() const;
  void set_lastackedpackettime(::uint64_t value);

  private:
  ::uint64_t _internal_lastackedpackettime() const;
  void _internal_set_lastackedpackettime(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.NMT_NetSpeed)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NMT_NetSpeed& from_msg);
    ::uint64_t lastackedpackettime_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlProtocol_2eproto;
};
// -------------------------------------------------------------------

class NMT_Login final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.NMT_Login) */ {
 public:
  inline NMT_Login() : NMT_Login(nullptr) {}
  ~NMT_Login() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NMT_Login* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NMT_Login));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NMT_Login(
      ::google::protobuf::internal::ConstantInitialized);

  inline NMT_Login(const NMT_Login& from) : NMT_Login(nullptr, from) {}
  inline NMT_Login(NMT_Login&& from) noexcept
      : NMT_Login(nullptr, std::move(from)) {}
  inline NMT_Login& operator=(const NMT_Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline NMT_Login& operator=(NMT_Login&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NMT_Login& default_instance() {
    return *internal_default_instance();
  }
  static inline const NMT_Login* internal_default_instance() {
    return reinterpret_cast<const NMT_Login*>(
        &_NMT_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(NMT_Login& a, NMT_Login& b) { a.Swap(&b); }
  inline void Swap(NMT_Login* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NMT_Login* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NMT_Login* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NMT_Login>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NMT_Login& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NMT_Login& from) { NMT_Login::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NMT_Login* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.NMT_Login"; }

 protected:
  explicit NMT_Login(::google::protobuf::Arena* arena);
  NMT_Login(::google::protobuf::Arena* arena, const NMT_Login& from);
  NMT_Login(::google::protobuf::Arena* arena, NMT_Login&& from) noexcept
      : NMT_Login(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 2,
    kPasswordFieldNumber = 3,
  };
  // string Id = 2;
  void clear_id() ;
  const std::string& id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* value);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // string Password = 3;
  void clear_password() ;
  const std::string& password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* value);

  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(
      const std::string& value);
  std::string* _internal_mutable_password();

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.NMT_Login)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      41, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NMT_Login& from_msg);
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlProtocol_2eproto;
};
// -------------------------------------------------------------------

class NMT_Join final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.NMT_Join) */ {
 public:
  inline NMT_Join() : NMT_Join(nullptr) {}
  ~NMT_Join() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NMT_Join* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NMT_Join));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NMT_Join(
      ::google::protobuf::internal::ConstantInitialized);

  inline NMT_Join(const NMT_Join& from) : NMT_Join(nullptr, from) {}
  inline NMT_Join(NMT_Join&& from) noexcept
      : NMT_Join(nullptr, std::move(from)) {}
  inline NMT_Join& operator=(const NMT_Join& from) {
    CopyFrom(from);
    return *this;
  }
  inline NMT_Join& operator=(NMT_Join&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NMT_Join& default_instance() {
    return *internal_default_instance();
  }
  static inline const NMT_Join* internal_default_instance() {
    return reinterpret_cast<const NMT_Join*>(
        &_NMT_Join_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(NMT_Join& a, NMT_Join& b) { a.Swap(&b); }
  inline void Swap(NMT_Join* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NMT_Join* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NMT_Join* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NMT_Join>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NMT_Join& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NMT_Join& from) { NMT_Join::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NMT_Join* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.NMT_Join"; }

 protected:
  explicit NMT_Join(::google::protobuf::Arena* arena);
  NMT_Join(::google::protobuf::Arena* arena, const NMT_Join& from);
  NMT_Join(::google::protobuf::Arena* arena, NMT_Join&& from) noexcept
      : NMT_Join(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResponseFieldNumber = 1,
  };
  // int32 Response = 1;
  void clear_response() ;
  ::int32_t response() const;
  void set_response(::int32_t value);

  private:
  ::int32_t _internal_response() const;
  void _internal_set_response(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.NMT_Join)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NMT_Join& from_msg);
    ::int32_t response_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlProtocol_2eproto;
};
// -------------------------------------------------------------------

class NMT_Hello final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.NMT_Hello) */ {
 public:
  inline NMT_Hello() : NMT_Hello(nullptr) {}
  ~NMT_Hello() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NMT_Hello* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NMT_Hello));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NMT_Hello(
      ::google::protobuf::internal::ConstantInitialized);

  inline NMT_Hello(const NMT_Hello& from) : NMT_Hello(nullptr, from) {}
  inline NMT_Hello(NMT_Hello&& from) noexcept
      : NMT_Hello(nullptr, std::move(from)) {}
  inline NMT_Hello& operator=(const NMT_Hello& from) {
    CopyFrom(from);
    return *this;
  }
  inline NMT_Hello& operator=(NMT_Hello&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NMT_Hello& default_instance() {
    return *internal_default_instance();
  }
  static inline const NMT_Hello* internal_default_instance() {
    return reinterpret_cast<const NMT_Hello*>(
        &_NMT_Hello_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NMT_Hello& a, NMT_Hello& b) { a.Swap(&b); }
  inline void Swap(NMT_Hello* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NMT_Hello* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NMT_Hello* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NMT_Hello>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NMT_Hello& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NMT_Hello& from) { NMT_Hello::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NMT_Hello* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.NMT_Hello"; }

 protected:
  explicit NMT_Hello(::google::protobuf::Arena* arena);
  NMT_Hello(::google::protobuf::Arena* arena, const NMT_Hello& from);
  NMT_Hello(::google::protobuf::Arena* arena, NMT_Hello&& from) noexcept
      : NMT_Hello(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTokenFieldNumber = 1,
    kNetworkIdFieldNumber = 2,
  };
  // string Token = 1;
  void clear_token() ;
  const std::string& token() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* value);

  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(
      const std::string& value);
  std::string* _internal_mutable_token();

  public:
  // int32 NetworkId = 2;
  void clear_networkid() ;
  ::int32_t networkid() const;
  void set_networkid(::int32_t value);

  private:
  ::int32_t _internal_networkid() const;
  void _internal_set_networkid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.NMT_Hello)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      36, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NMT_Hello& from_msg);
    ::google::protobuf::internal::ArenaStringPtr token_;
    ::int32_t networkid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlProtocol_2eproto;
};
// -------------------------------------------------------------------

class NMT_Failure final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.NMT_Failure) */ {
 public:
  inline NMT_Failure() : NMT_Failure(nullptr) {}
  ~NMT_Failure() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NMT_Failure* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NMT_Failure));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NMT_Failure(
      ::google::protobuf::internal::ConstantInitialized);

  inline NMT_Failure(const NMT_Failure& from) : NMT_Failure(nullptr, from) {}
  inline NMT_Failure(NMT_Failure&& from) noexcept
      : NMT_Failure(nullptr, std::move(from)) {}
  inline NMT_Failure& operator=(const NMT_Failure& from) {
    CopyFrom(from);
    return *this;
  }
  inline NMT_Failure& operator=(NMT_Failure&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NMT_Failure& default_instance() {
    return *internal_default_instance();
  }
  static inline const NMT_Failure* internal_default_instance() {
    return reinterpret_cast<const NMT_Failure*>(
        &_NMT_Failure_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(NMT_Failure& a, NMT_Failure& b) { a.Swap(&b); }
  inline void Swap(NMT_Failure* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NMT_Failure* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NMT_Failure* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NMT_Failure>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NMT_Failure& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NMT_Failure& from) { NMT_Failure::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NMT_Failure* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.NMT_Failure"; }

 protected:
  explicit NMT_Failure(::google::protobuf::Arena* arena);
  NMT_Failure(::google::protobuf::Arena* arena, const NMT_Failure& from);
  NMT_Failure(::google::protobuf::Arena* arena, NMT_Failure&& from) noexcept
      : NMT_Failure(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorTypeFieldNumber = 1,
    kErrorNumFieldNumber = 2,
  };
  // int32 ErrorType = 1;
  void clear_errortype() ;
  ::int32_t errortype() const;
  void set_errortype(::int32_t value);

  private:
  ::int32_t _internal_errortype() const;
  void _internal_set_errortype(::int32_t value);

  public:
  // int32 ErrorNum = 2;
  void clear_errornum() ;
  ::int32_t errornum() const;
  void set_errornum(::int32_t value);

  private:
  ::int32_t _internal_errornum() const;
  void _internal_set_errornum(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.NMT_Failure)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NMT_Failure& from_msg);
    ::int32_t errortype_;
    ::int32_t errornum_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlProtocol_2eproto;
};
// -------------------------------------------------------------------

class NMT_Challenge final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.NMT_Challenge) */ {
 public:
  inline NMT_Challenge() : NMT_Challenge(nullptr) {}
  ~NMT_Challenge() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NMT_Challenge* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NMT_Challenge));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NMT_Challenge(
      ::google::protobuf::internal::ConstantInitialized);

  inline NMT_Challenge(const NMT_Challenge& from) : NMT_Challenge(nullptr, from) {}
  inline NMT_Challenge(NMT_Challenge&& from) noexcept
      : NMT_Challenge(nullptr, std::move(from)) {}
  inline NMT_Challenge& operator=(const NMT_Challenge& from) {
    CopyFrom(from);
    return *this;
  }
  inline NMT_Challenge& operator=(NMT_Challenge&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NMT_Challenge& default_instance() {
    return *internal_default_instance();
  }
  static inline const NMT_Challenge* internal_default_instance() {
    return reinterpret_cast<const NMT_Challenge*>(
        &_NMT_Challenge_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(NMT_Challenge& a, NMT_Challenge& b) { a.Swap(&b); }
  inline void Swap(NMT_Challenge* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NMT_Challenge* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NMT_Challenge* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NMT_Challenge>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NMT_Challenge& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NMT_Challenge& from) { NMT_Challenge::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NMT_Challenge* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.NMT_Challenge"; }

 protected:
  explicit NMT_Challenge(::google::protobuf::Arena* arena);
  NMT_Challenge(::google::protobuf::Arena* arena, const NMT_Challenge& from);
  NMT_Challenge(::google::protobuf::Arena* arena, NMT_Challenge&& from) noexcept
      : NMT_Challenge(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOptionFieldNumber = 1,
    kURLFieldNumber = 2,
  };
  // string Option = 1;
  void clear_option() ;
  const std::string& option() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_option(Arg_&& arg, Args_... args);
  std::string* mutable_option();
  PROTOBUF_NODISCARD std::string* release_option();
  void set_allocated_option(std::string* value);

  private:
  const std::string& _internal_option() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_option(
      const std::string& value);
  std::string* _internal_mutable_option();

  public:
  // string URL = 2;
  void clear_url() ;
  const std::string& url() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_url(Arg_&& arg, Args_... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* value);

  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(
      const std::string& value);
  std::string* _internal_mutable_url();

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.NMT_Challenge)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      44, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NMT_Challenge& from_msg);
    ::google::protobuf::internal::ArenaStringPtr option_;
    ::google::protobuf::internal::ArenaStringPtr url_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlProtocol_2eproto;
};
// -------------------------------------------------------------------

class NMT_Welcome final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GameProtocol.NMT_Welcome) */ {
 public:
  inline NMT_Welcome() : NMT_Welcome(nullptr) {}
  ~NMT_Welcome() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NMT_Welcome* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NMT_Welcome));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NMT_Welcome(
      ::google::protobuf::internal::ConstantInitialized);

  inline NMT_Welcome(const NMT_Welcome& from) : NMT_Welcome(nullptr, from) {}
  inline NMT_Welcome(NMT_Welcome&& from) noexcept
      : NMT_Welcome(nullptr, std::move(from)) {}
  inline NMT_Welcome& operator=(const NMT_Welcome& from) {
    CopyFrom(from);
    return *this;
  }
  inline NMT_Welcome& operator=(NMT_Welcome&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NMT_Welcome& default_instance() {
    return *internal_default_instance();
  }
  static inline const NMT_Welcome* internal_default_instance() {
    return reinterpret_cast<const NMT_Welcome*>(
        &_NMT_Welcome_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(NMT_Welcome& a, NMT_Welcome& b) { a.Swap(&b); }
  inline void Swap(NMT_Welcome* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NMT_Welcome* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NMT_Welcome* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NMT_Welcome>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NMT_Welcome& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NMT_Welcome& from) { NMT_Welcome::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NMT_Welcome* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GameProtocol.NMT_Welcome"; }

 protected:
  explicit NMT_Welcome(::google::protobuf::Arena* arena);
  NMT_Welcome(::google::protobuf::Arena* arena, const NMT_Welcome& from);
  NMT_Welcome(::google::protobuf::Arena* arena, NMT_Welcome&& from) noexcept
      : NMT_Welcome(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGameNameFieldNumber = 1,
    kWorldNameFieldNumber = 2,
    kPlayerCharacterFieldNumber = 3,
  };
  // string GameName = 1;
  void clear_gamename() ;
  const std::string& gamename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_gamename(Arg_&& arg, Args_... args);
  std::string* mutable_gamename();
  PROTOBUF_NODISCARD std::string* release_gamename();
  void set_allocated_gamename(std::string* value);

  private:
  const std::string& _internal_gamename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_gamename(
      const std::string& value);
  std::string* _internal_mutable_gamename();

  public:
  // string WorldName = 2;
  void clear_worldname() ;
  const std::string& worldname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_worldname(Arg_&& arg, Args_... args);
  std::string* mutable_worldname();
  PROTOBUF_NODISCARD std::string* release_worldname();
  void set_allocated_worldname(std::string* value);

  private:
  const std::string& _internal_worldname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_worldname(
      const std::string& value);
  std::string* _internal_mutable_worldname();

  public:
  // .GameProtocol.Character PlayerCharacter = 3;
  bool has_playercharacter() const;
  void clear_playercharacter() ;
  const ::GameProtocol::Character& playercharacter() const;
  PROTOBUF_NODISCARD ::GameProtocol::Character* release_playercharacter();
  ::GameProtocol::Character* mutable_playercharacter();
  void set_allocated_playercharacter(::GameProtocol::Character* value);
  void unsafe_arena_set_allocated_playercharacter(::GameProtocol::Character* value);
  ::GameProtocol::Character* unsafe_arena_release_playercharacter();

  private:
  const ::GameProtocol::Character& _internal_playercharacter() const;
  ::GameProtocol::Character* _internal_mutable_playercharacter();

  public:
  // @@protoc_insertion_point(class_scope:GameProtocol.NMT_Welcome)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      50, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NMT_Welcome& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr gamename_;
    ::google::protobuf::internal::ArenaStringPtr worldname_;
    ::GameProtocol::Character* playercharacter_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlProtocol_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NMT_Hello

// string Token = 1;
inline void NMT_Hello::clear_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.ClearToEmpty();
}
inline const std::string& NMT_Hello::token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Hello.Token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NMT_Hello::set_token(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Hello.Token)
}
inline std::string* NMT_Hello::mutable_token() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Hello.Token)
  return _s;
}
inline const std::string& NMT_Hello::_internal_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.token_.Get();
}
inline void NMT_Hello::_internal_set_token(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.Set(value, GetArena());
}
inline std::string* NMT_Hello::_internal_mutable_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.token_.Mutable( GetArena());
}
inline std::string* NMT_Hello::release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Hello.Token)
  return _impl_.token_.Release();
}
inline void NMT_Hello::set_allocated_token(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Hello.Token)
}

// int32 NetworkId = 2;
inline void NMT_Hello::clear_networkid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.networkid_ = 0;
}
inline ::int32_t NMT_Hello::networkid() const {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Hello.NetworkId)
  return _internal_networkid();
}
inline void NMT_Hello::set_networkid(::int32_t value) {
  _internal_set_networkid(value);
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Hello.NetworkId)
}
inline ::int32_t NMT_Hello::_internal_networkid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.networkid_;
}
inline void NMT_Hello::_internal_set_networkid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.networkid_ = value;
}

// -------------------------------------------------------------------

// NMT_Challenge

// string Option = 1;
inline void NMT_Challenge::clear_option() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.option_.ClearToEmpty();
}
inline const std::string& NMT_Challenge::option() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Challenge.Option)
  return _internal_option();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NMT_Challenge::set_option(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.option_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Challenge.Option)
}
inline std::string* NMT_Challenge::mutable_option() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_option();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Challenge.Option)
  return _s;
}
inline const std::string& NMT_Challenge::_internal_option() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.option_.Get();
}
inline void NMT_Challenge::_internal_set_option(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.option_.Set(value, GetArena());
}
inline std::string* NMT_Challenge::_internal_mutable_option() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.option_.Mutable( GetArena());
}
inline std::string* NMT_Challenge::release_option() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Challenge.Option)
  return _impl_.option_.Release();
}
inline void NMT_Challenge::set_allocated_option(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.option_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.option_.IsDefault()) {
    _impl_.option_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Challenge.Option)
}

// string URL = 2;
inline void NMT_Challenge::clear_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.ClearToEmpty();
}
inline const std::string& NMT_Challenge::url() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Challenge.URL)
  return _internal_url();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NMT_Challenge::set_url(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Challenge.URL)
}
inline std::string* NMT_Challenge::mutable_url() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Challenge.URL)
  return _s;
}
inline const std::string& NMT_Challenge::_internal_url() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.url_.Get();
}
inline void NMT_Challenge::_internal_set_url(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.Set(value, GetArena());
}
inline std::string* NMT_Challenge::_internal_mutable_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.url_.Mutable( GetArena());
}
inline std::string* NMT_Challenge::release_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Challenge.URL)
  return _impl_.url_.Release();
}
inline void NMT_Challenge::set_allocated_url(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Challenge.URL)
}

// -------------------------------------------------------------------

// NMT_Login

// string Id = 2;
inline void NMT_Login::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
}
inline const std::string& NMT_Login::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Login.Id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NMT_Login::set_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Login.Id)
}
inline std::string* NMT_Login::mutable_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Login.Id)
  return _s;
}
inline const std::string& NMT_Login::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void NMT_Login::_internal_set_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline std::string* NMT_Login::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline std::string* NMT_Login::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Login.Id)
  return _impl_.id_.Release();
}
inline void NMT_Login::set_allocated_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Login.Id)
}

// string Password = 3;
inline void NMT_Login::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
}
inline const std::string& NMT_Login::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Login.Password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NMT_Login::set_password(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Login.Password)
}
inline std::string* NMT_Login::mutable_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Login.Password)
  return _s;
}
inline const std::string& NMT_Login::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void NMT_Login::_internal_set_password(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline std::string* NMT_Login::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline std::string* NMT_Login::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Login.Password)
  return _impl_.password_.Release();
}
inline void NMT_Login::set_allocated_password(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Login.Password)
}

// -------------------------------------------------------------------

// NMT_Welcome

// string GameName = 1;
inline void NMT_Welcome::clear_gamename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamename_.ClearToEmpty();
}
inline const std::string& NMT_Welcome::gamename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Welcome.GameName)
  return _internal_gamename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NMT_Welcome::set_gamename(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Welcome.GameName)
}
inline std::string* NMT_Welcome::mutable_gamename() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_gamename();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Welcome.GameName)
  return _s;
}
inline const std::string& NMT_Welcome::_internal_gamename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gamename_.Get();
}
inline void NMT_Welcome::_internal_set_gamename(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamename_.Set(value, GetArena());
}
inline std::string* NMT_Welcome::_internal_mutable_gamename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.gamename_.Mutable( GetArena());
}
inline std::string* NMT_Welcome::release_gamename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Welcome.GameName)
  return _impl_.gamename_.Release();
}
inline void NMT_Welcome::set_allocated_gamename(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.gamename_.IsDefault()) {
    _impl_.gamename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Welcome.GameName)
}

// string WorldName = 2;
inline void NMT_Welcome::clear_worldname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worldname_.ClearToEmpty();
}
inline const std::string& NMT_Welcome::worldname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Welcome.WorldName)
  return _internal_worldname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NMT_Welcome::set_worldname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worldname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Welcome.WorldName)
}
inline std::string* NMT_Welcome::mutable_worldname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_worldname();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Welcome.WorldName)
  return _s;
}
inline const std::string& NMT_Welcome::_internal_worldname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.worldname_.Get();
}
inline void NMT_Welcome::_internal_set_worldname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worldname_.Set(value, GetArena());
}
inline std::string* NMT_Welcome::_internal_mutable_worldname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.worldname_.Mutable( GetArena());
}
inline std::string* NMT_Welcome::release_worldname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Welcome.WorldName)
  return _impl_.worldname_.Release();
}
inline void NMT_Welcome::set_allocated_worldname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worldname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.worldname_.IsDefault()) {
    _impl_.worldname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Welcome.WorldName)
}

// .GameProtocol.Character PlayerCharacter = 3;
inline bool NMT_Welcome::has_playercharacter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.playercharacter_ != nullptr);
  return value;
}
inline const ::GameProtocol::Character& NMT_Welcome::_internal_playercharacter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameProtocol::Character* p = _impl_.playercharacter_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameProtocol::Character&>(::GameProtocol::_Character_default_instance_);
}
inline const ::GameProtocol::Character& NMT_Welcome::playercharacter() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Welcome.PlayerCharacter)
  return _internal_playercharacter();
}
inline void NMT_Welcome::unsafe_arena_set_allocated_playercharacter(::GameProtocol::Character* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.playercharacter_);
  }
  _impl_.playercharacter_ = reinterpret_cast<::GameProtocol::Character*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameProtocol.NMT_Welcome.PlayerCharacter)
}
inline ::GameProtocol::Character* NMT_Welcome::release_playercharacter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Character* released = _impl_.playercharacter_;
  _impl_.playercharacter_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameProtocol::Character* NMT_Welcome::unsafe_arena_release_playercharacter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GameProtocol.NMT_Welcome.PlayerCharacter)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::GameProtocol::Character* temp = _impl_.playercharacter_;
  _impl_.playercharacter_ = nullptr;
  return temp;
}
inline ::GameProtocol::Character* NMT_Welcome::_internal_mutable_playercharacter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.playercharacter_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameProtocol::Character>(GetArena());
    _impl_.playercharacter_ = reinterpret_cast<::GameProtocol::Character*>(p);
  }
  return _impl_.playercharacter_;
}
inline ::GameProtocol::Character* NMT_Welcome::mutable_playercharacter() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::GameProtocol::Character* _msg = _internal_mutable_playercharacter();
  // @@protoc_insertion_point(field_mutable:GameProtocol.NMT_Welcome.PlayerCharacter)
  return _msg;
}
inline void NMT_Welcome::set_allocated_playercharacter(::GameProtocol::Character* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.playercharacter_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.playercharacter_ = reinterpret_cast<::GameProtocol::Character*>(value);
  // @@protoc_insertion_point(field_set_allocated:GameProtocol.NMT_Welcome.PlayerCharacter)
}

// -------------------------------------------------------------------

// NMT_Join

// int32 Response = 1;
inline void NMT_Join::clear_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_ = 0;
}
inline ::int32_t NMT_Join::response() const {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Join.Response)
  return _internal_response();
}
inline void NMT_Join::set_response(::int32_t value) {
  _internal_set_response(value);
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Join.Response)
}
inline ::int32_t NMT_Join::_internal_response() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.response_;
}
inline void NMT_Join::_internal_set_response(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_ = value;
}

// -------------------------------------------------------------------

// NMT_NetSpeed

// uint64 LastAckedPacketTime = 1;
inline void NMT_NetSpeed::clear_lastackedpackettime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastackedpackettime_ = ::uint64_t{0u};
}
inline ::uint64_t NMT_NetSpeed::lastackedpackettime() const {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_NetSpeed.LastAckedPacketTime)
  return _internal_lastackedpackettime();
}
inline void NMT_NetSpeed::set_lastackedpackettime(::uint64_t value) {
  _internal_set_lastackedpackettime(value);
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_NetSpeed.LastAckedPacketTime)
}
inline ::uint64_t NMT_NetSpeed::_internal_lastackedpackettime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lastackedpackettime_;
}
inline void NMT_NetSpeed::_internal_set_lastackedpackettime(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastackedpackettime_ = value;
}

// -------------------------------------------------------------------

// NMT_Failure

// int32 ErrorType = 1;
inline void NMT_Failure::clear_errortype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errortype_ = 0;
}
inline ::int32_t NMT_Failure::errortype() const {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Failure.ErrorType)
  return _internal_errortype();
}
inline void NMT_Failure::set_errortype(::int32_t value) {
  _internal_set_errortype(value);
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Failure.ErrorType)
}
inline ::int32_t NMT_Failure::_internal_errortype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errortype_;
}
inline void NMT_Failure::_internal_set_errortype(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errortype_ = value;
}

// int32 ErrorNum = 2;
inline void NMT_Failure::clear_errornum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errornum_ = 0;
}
inline ::int32_t NMT_Failure::errornum() const {
  // @@protoc_insertion_point(field_get:GameProtocol.NMT_Failure.ErrorNum)
  return _internal_errornum();
}
inline void NMT_Failure::set_errornum(::int32_t value) {
  _internal_set_errornum(value);
  // @@protoc_insertion_point(field_set:GameProtocol.NMT_Failure.ErrorNum)
}
inline ::int32_t NMT_Failure::_internal_errornum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errornum_;
}
inline void NMT_Failure::_internal_set_errornum(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errornum_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GameProtocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ControlProtocol_2eproto_2epb_2eh
