// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ControlProtocol.proto
// Protobuf C++ Version: 5.29.3

#include "ControlProtocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GameProtocol {

inline constexpr NMT_NetSpeed::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : lastackedpackettime_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NMT_NetSpeed::NMT_NetSpeed(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NMT_NetSpeedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NMT_NetSpeedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NMT_NetSpeedDefaultTypeInternal() {}
  union {
    NMT_NetSpeed _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NMT_NetSpeedDefaultTypeInternal _NMT_NetSpeed_default_instance_;

inline constexpr NMT_Login::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NMT_Login::NMT_Login(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NMT_LoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NMT_LoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NMT_LoginDefaultTypeInternal() {}
  union {
    NMT_Login _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NMT_LoginDefaultTypeInternal _NMT_Login_default_instance_;

inline constexpr NMT_Join::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : response_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NMT_Join::NMT_Join(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NMT_JoinDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NMT_JoinDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NMT_JoinDefaultTypeInternal() {}
  union {
    NMT_Join _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NMT_JoinDefaultTypeInternal _NMT_Join_default_instance_;

inline constexpr NMT_Hello::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        networkid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NMT_Hello::NMT_Hello(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NMT_HelloDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NMT_HelloDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NMT_HelloDefaultTypeInternal() {}
  union {
    NMT_Hello _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NMT_HelloDefaultTypeInternal _NMT_Hello_default_instance_;

inline constexpr NMT_Failure::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : errortype_{0},
        errornum_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NMT_Failure::NMT_Failure(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NMT_FailureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NMT_FailureDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NMT_FailureDefaultTypeInternal() {}
  union {
    NMT_Failure _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NMT_FailureDefaultTypeInternal _NMT_Failure_default_instance_;

inline constexpr NMT_Challenge::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : option_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        url_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NMT_Challenge::NMT_Challenge(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NMT_ChallengeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NMT_ChallengeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NMT_ChallengeDefaultTypeInternal() {}
  union {
    NMT_Challenge _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NMT_ChallengeDefaultTypeInternal _NMT_Challenge_default_instance_;

inline constexpr NMT_Welcome::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        gamename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        worldname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        playercharacter_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR NMT_Welcome::NMT_Welcome(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NMT_WelcomeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NMT_WelcomeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NMT_WelcomeDefaultTypeInternal() {}
  union {
    NMT_Welcome _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NMT_WelcomeDefaultTypeInternal _NMT_Welcome_default_instance_;
}  // namespace GameProtocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ControlProtocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ControlProtocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_ControlProtocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Hello, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Hello, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Hello, _impl_.networkid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Challenge, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Challenge, _impl_.option_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Challenge, _impl_.url_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Login, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Login, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Login, _impl_.password_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Welcome, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Welcome, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Welcome, _impl_.gamename_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Welcome, _impl_.worldname_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Welcome, _impl_.playercharacter_),
        ~0u,
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Join, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Join, _impl_.response_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_NetSpeed, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_NetSpeed, _impl_.lastackedpackettime_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Failure, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Failure, _impl_.errortype_),
        PROTOBUF_FIELD_OFFSET(::GameProtocol::NMT_Failure, _impl_.errornum_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::GameProtocol::NMT_Hello)},
        {10, -1, -1, sizeof(::GameProtocol::NMT_Challenge)},
        {20, -1, -1, sizeof(::GameProtocol::NMT_Login)},
        {30, 41, -1, sizeof(::GameProtocol::NMT_Welcome)},
        {44, -1, -1, sizeof(::GameProtocol::NMT_Join)},
        {53, -1, -1, sizeof(::GameProtocol::NMT_NetSpeed)},
        {62, -1, -1, sizeof(::GameProtocol::NMT_Failure)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::GameProtocol::_NMT_Hello_default_instance_._instance,
    &::GameProtocol::_NMT_Challenge_default_instance_._instance,
    &::GameProtocol::_NMT_Login_default_instance_._instance,
    &::GameProtocol::_NMT_Welcome_default_instance_._instance,
    &::GameProtocol::_NMT_Join_default_instance_._instance,
    &::GameProtocol::_NMT_NetSpeed_default_instance_._instance,
    &::GameProtocol::_NMT_Failure_default_instance_._instance,
};
const char descriptor_table_protodef_ControlProtocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025ControlProtocol.proto\022\014GameProtocol\032\014S"
    "truct.proto\"-\n\tNMT_Hello\022\r\n\005Token\030\001 \001(\t\022"
    "\021\n\tNetworkId\030\002 \001(\005\",\n\rNMT_Challenge\022\016\n\006O"
    "ption\030\001 \001(\t\022\013\n\003URL\030\002 \001(\t\")\n\tNMT_Login\022\n\n"
    "\002Id\030\002 \001(\t\022\020\n\010Password\030\003 \001(\t\"d\n\013NMT_Welco"
    "me\022\020\n\010GameName\030\001 \001(\t\022\021\n\tWorldName\030\002 \001(\t\022"
    "0\n\017PlayerCharacter\030\003 \001(\0132\027.GameProtocol."
    "Character\"\034\n\010NMT_Join\022\020\n\010Response\030\001 \001(\005\""
    "+\n\014NMT_NetSpeed\022\033\n\023LastAckedPacketTime\030\001"
    " \001(\004\"2\n\013NMT_Failure\022\021\n\tErrorType\030\001 \001(\005\022\020"
    "\n\010ErrorNum\030\002 \001(\005b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_ControlProtocol_2eproto_deps[1] =
    {
        &::descriptor_table_Struct_2eproto,
};
static ::absl::once_flag descriptor_table_ControlProtocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ControlProtocol_2eproto = {
    false,
    false,
    424,
    descriptor_table_protodef_ControlProtocol_2eproto,
    "ControlProtocol.proto",
    &descriptor_table_ControlProtocol_2eproto_once,
    descriptor_table_ControlProtocol_2eproto_deps,
    1,
    7,
    schemas,
    file_default_instances,
    TableStruct_ControlProtocol_2eproto::offsets,
    file_level_enum_descriptors_ControlProtocol_2eproto,
    file_level_service_descriptors_ControlProtocol_2eproto,
};
namespace GameProtocol {
// ===================================================================

class NMT_Hello::_Internal {
 public:
};

NMT_Hello::NMT_Hello(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.NMT_Hello)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Hello::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::NMT_Hello& from_msg)
      : token_(arena, from.token_),
        _cached_size_{0} {}

NMT_Hello::NMT_Hello(
    ::google::protobuf::Arena* arena,
    const NMT_Hello& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NMT_Hello* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.networkid_ = from._impl_.networkid_;

  // @@protoc_insertion_point(copy_constructor:GameProtocol.NMT_Hello)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Hello::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void NMT_Hello::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.networkid_ = {};
}
NMT_Hello::~NMT_Hello() {
  // @@protoc_insertion_point(destructor:GameProtocol.NMT_Hello)
  SharedDtor(*this);
}
inline void NMT_Hello::SharedDtor(MessageLite& self) {
  NMT_Hello& this_ = static_cast<NMT_Hello&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* NMT_Hello::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NMT_Hello(arena);
}
constexpr auto NMT_Hello::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NMT_Hello),
                                            alignof(NMT_Hello));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NMT_Hello::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NMT_Hello_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NMT_Hello::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NMT_Hello>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NMT_Hello::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NMT_Hello>(), &NMT_Hello::ByteSizeLong,
            &NMT_Hello::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NMT_Hello, _impl_._cached_size_),
        false,
    },
    &NMT_Hello::kDescriptorMethods,
    &descriptor_table_ControlProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NMT_Hello::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2> NMT_Hello::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::NMT_Hello>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 NetworkId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NMT_Hello, _impl_.networkid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Hello, _impl_.networkid_)}},
    // string Token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Hello, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Token = 1;
    {PROTOBUF_FIELD_OFFSET(NMT_Hello, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 NetworkId = 2;
    {PROTOBUF_FIELD_OFFSET(NMT_Hello, _impl_.networkid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\26\5\0\0\0\0\0\0"
    "GameProtocol.NMT_Hello"
    "Token"
  }},
};

PROTOBUF_NOINLINE void NMT_Hello::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.NMT_Hello)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.networkid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NMT_Hello::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NMT_Hello& this_ = static_cast<const NMT_Hello&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NMT_Hello::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NMT_Hello& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.NMT_Hello)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string Token = 1;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameProtocol.NMT_Hello.Token");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 NetworkId = 2;
          if (this_._internal_networkid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_networkid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.NMT_Hello)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NMT_Hello::ByteSizeLong(const MessageLite& base) {
          const NMT_Hello& this_ = static_cast<const NMT_Hello&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NMT_Hello::ByteSizeLong() const {
          const NMT_Hello& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.NMT_Hello)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string Token = 1;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // int32 NetworkId = 2;
            if (this_._internal_networkid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_networkid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NMT_Hello::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NMT_Hello*>(&to_msg);
  auto& from = static_cast<const NMT_Hello&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.NMT_Hello)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_networkid() != 0) {
    _this->_impl_.networkid_ = from._impl_.networkid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NMT_Hello::CopyFrom(const NMT_Hello& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.NMT_Hello)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NMT_Hello::InternalSwap(NMT_Hello* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
        swap(_impl_.networkid_, other->_impl_.networkid_);
}

::google::protobuf::Metadata NMT_Hello::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NMT_Challenge::_Internal {
 public:
};

NMT_Challenge::NMT_Challenge(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.NMT_Challenge)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Challenge::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::NMT_Challenge& from_msg)
      : option_(arena, from.option_),
        url_(arena, from.url_),
        _cached_size_{0} {}

NMT_Challenge::NMT_Challenge(
    ::google::protobuf::Arena* arena,
    const NMT_Challenge& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NMT_Challenge* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GameProtocol.NMT_Challenge)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Challenge::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : option_(arena),
        url_(arena),
        _cached_size_{0} {}

inline void NMT_Challenge::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NMT_Challenge::~NMT_Challenge() {
  // @@protoc_insertion_point(destructor:GameProtocol.NMT_Challenge)
  SharedDtor(*this);
}
inline void NMT_Challenge::SharedDtor(MessageLite& self) {
  NMT_Challenge& this_ = static_cast<NMT_Challenge&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.option_.Destroy();
  this_._impl_.url_.Destroy();
  this_._impl_.~Impl_();
}

inline void* NMT_Challenge::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NMT_Challenge(arena);
}
constexpr auto NMT_Challenge::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NMT_Challenge),
                                            alignof(NMT_Challenge));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NMT_Challenge::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NMT_Challenge_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NMT_Challenge::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NMT_Challenge>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NMT_Challenge::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NMT_Challenge>(), &NMT_Challenge::ByteSizeLong,
            &NMT_Challenge::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NMT_Challenge, _impl_._cached_size_),
        false,
    },
    &NMT_Challenge::kDescriptorMethods,
    &descriptor_table_ControlProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NMT_Challenge::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2> NMT_Challenge::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::NMT_Challenge>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string URL = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Challenge, _impl_.url_)}},
    // string Option = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Challenge, _impl_.option_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Option = 1;
    {PROTOBUF_FIELD_OFFSET(NMT_Challenge, _impl_.option_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string URL = 2;
    {PROTOBUF_FIELD_OFFSET(NMT_Challenge, _impl_.url_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\6\3\0\0\0\0\0"
    "GameProtocol.NMT_Challenge"
    "Option"
    "URL"
  }},
};

PROTOBUF_NOINLINE void NMT_Challenge::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.NMT_Challenge)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.option_.ClearToEmpty();
  _impl_.url_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NMT_Challenge::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NMT_Challenge& this_ = static_cast<const NMT_Challenge&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NMT_Challenge::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NMT_Challenge& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.NMT_Challenge)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string Option = 1;
          if (!this_._internal_option().empty()) {
            const std::string& _s = this_._internal_option();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameProtocol.NMT_Challenge.Option");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string URL = 2;
          if (!this_._internal_url().empty()) {
            const std::string& _s = this_._internal_url();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameProtocol.NMT_Challenge.URL");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.NMT_Challenge)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NMT_Challenge::ByteSizeLong(const MessageLite& base) {
          const NMT_Challenge& this_ = static_cast<const NMT_Challenge&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NMT_Challenge::ByteSizeLong() const {
          const NMT_Challenge& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.NMT_Challenge)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string Option = 1;
            if (!this_._internal_option().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_option());
            }
            // string URL = 2;
            if (!this_._internal_url().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_url());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NMT_Challenge::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NMT_Challenge*>(&to_msg);
  auto& from = static_cast<const NMT_Challenge&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.NMT_Challenge)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_option().empty()) {
    _this->_internal_set_option(from._internal_option());
  }
  if (!from._internal_url().empty()) {
    _this->_internal_set_url(from._internal_url());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NMT_Challenge::CopyFrom(const NMT_Challenge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.NMT_Challenge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NMT_Challenge::InternalSwap(NMT_Challenge* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.option_, &other->_impl_.option_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.url_, &other->_impl_.url_, arena);
}

::google::protobuf::Metadata NMT_Challenge::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NMT_Login::_Internal {
 public:
};

NMT_Login::NMT_Login(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.NMT_Login)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Login::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::NMT_Login& from_msg)
      : id_(arena, from.id_),
        password_(arena, from.password_),
        _cached_size_{0} {}

NMT_Login::NMT_Login(
    ::google::protobuf::Arena* arena,
    const NMT_Login& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NMT_Login* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GameProtocol.NMT_Login)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Login::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        password_(arena),
        _cached_size_{0} {}

inline void NMT_Login::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NMT_Login::~NMT_Login() {
  // @@protoc_insertion_point(destructor:GameProtocol.NMT_Login)
  SharedDtor(*this);
}
inline void NMT_Login::SharedDtor(MessageLite& self) {
  NMT_Login& this_ = static_cast<NMT_Login&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.password_.Destroy();
  this_._impl_.~Impl_();
}

inline void* NMT_Login::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NMT_Login(arena);
}
constexpr auto NMT_Login::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NMT_Login),
                                            alignof(NMT_Login));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NMT_Login::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NMT_Login_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NMT_Login::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NMT_Login>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NMT_Login::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NMT_Login>(), &NMT_Login::ByteSizeLong,
            &NMT_Login::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NMT_Login, _impl_._cached_size_),
        false,
    },
    &NMT_Login::kDescriptorMethods,
    &descriptor_table_ControlProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NMT_Login::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> NMT_Login::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967289,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::NMT_Login>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string Id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Login, _impl_.id_)}},
    // string Password = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Login, _impl_.password_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Id = 2;
    {PROTOBUF_FIELD_OFFSET(NMT_Login, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Password = 3;
    {PROTOBUF_FIELD_OFFSET(NMT_Login, _impl_.password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\2\10\0\0\0\0\0"
    "GameProtocol.NMT_Login"
    "Id"
    "Password"
  }},
};

PROTOBUF_NOINLINE void NMT_Login::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.NMT_Login)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NMT_Login::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NMT_Login& this_ = static_cast<const NMT_Login&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NMT_Login::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NMT_Login& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.NMT_Login)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string Id = 2;
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameProtocol.NMT_Login.Id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string Password = 3;
          if (!this_._internal_password().empty()) {
            const std::string& _s = this_._internal_password();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameProtocol.NMT_Login.Password");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.NMT_Login)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NMT_Login::ByteSizeLong(const MessageLite& base) {
          const NMT_Login& this_ = static_cast<const NMT_Login&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NMT_Login::ByteSizeLong() const {
          const NMT_Login& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.NMT_Login)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string Id = 2;
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
            // string Password = 3;
            if (!this_._internal_password().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_password());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NMT_Login::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NMT_Login*>(&to_msg);
  auto& from = static_cast<const NMT_Login&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.NMT_Login)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NMT_Login::CopyFrom(const NMT_Login& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.NMT_Login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NMT_Login::InternalSwap(NMT_Login* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
}

::google::protobuf::Metadata NMT_Login::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NMT_Welcome::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NMT_Welcome>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_._has_bits_);
};

void NMT_Welcome::clear_playercharacter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.playercharacter_ != nullptr) _impl_.playercharacter_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
NMT_Welcome::NMT_Welcome(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.NMT_Welcome)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Welcome::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GameProtocol::NMT_Welcome& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        gamename_(arena, from.gamename_),
        worldname_(arena, from.worldname_) {}

NMT_Welcome::NMT_Welcome(
    ::google::protobuf::Arena* arena,
    const NMT_Welcome& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NMT_Welcome* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.playercharacter_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::GameProtocol::Character>(
                              arena, *from._impl_.playercharacter_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:GameProtocol.NMT_Welcome)
}
inline PROTOBUF_NDEBUG_INLINE NMT_Welcome::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        gamename_(arena),
        worldname_(arena) {}

inline void NMT_Welcome::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.playercharacter_ = {};
}
NMT_Welcome::~NMT_Welcome() {
  // @@protoc_insertion_point(destructor:GameProtocol.NMT_Welcome)
  SharedDtor(*this);
}
inline void NMT_Welcome::SharedDtor(MessageLite& self) {
  NMT_Welcome& this_ = static_cast<NMT_Welcome&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.gamename_.Destroy();
  this_._impl_.worldname_.Destroy();
  delete this_._impl_.playercharacter_;
  this_._impl_.~Impl_();
}

inline void* NMT_Welcome::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NMT_Welcome(arena);
}
constexpr auto NMT_Welcome::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NMT_Welcome),
                                            alignof(NMT_Welcome));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NMT_Welcome::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NMT_Welcome_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NMT_Welcome::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NMT_Welcome>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NMT_Welcome::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NMT_Welcome>(), &NMT_Welcome::ByteSizeLong,
            &NMT_Welcome::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_._cached_size_),
        false,
    },
    &NMT_Welcome::kDescriptorMethods,
    &descriptor_table_ControlProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NMT_Welcome::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 50, 2> NMT_Welcome::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::NMT_Welcome>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string GameName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_.gamename_)}},
    // string WorldName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_.worldname_)}},
    // .GameProtocol.Character PlayerCharacter = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_.playercharacter_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string GameName = 1;
    {PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_.gamename_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string WorldName = 2;
    {PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_.worldname_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .GameProtocol.Character PlayerCharacter = 3;
    {PROTOBUF_FIELD_OFFSET(NMT_Welcome, _impl_.playercharacter_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::GameProtocol::Character>()},
  }}, {{
    "\30\10\11\0\0\0\0\0"
    "GameProtocol.NMT_Welcome"
    "GameName"
    "WorldName"
  }},
};

PROTOBUF_NOINLINE void NMT_Welcome::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.NMT_Welcome)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.gamename_.ClearToEmpty();
  _impl_.worldname_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.playercharacter_ != nullptr);
    _impl_.playercharacter_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NMT_Welcome::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NMT_Welcome& this_ = static_cast<const NMT_Welcome&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NMT_Welcome::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NMT_Welcome& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.NMT_Welcome)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string GameName = 1;
          if (!this_._internal_gamename().empty()) {
            const std::string& _s = this_._internal_gamename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameProtocol.NMT_Welcome.GameName");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string WorldName = 2;
          if (!this_._internal_worldname().empty()) {
            const std::string& _s = this_._internal_worldname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GameProtocol.NMT_Welcome.WorldName");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .GameProtocol.Character PlayerCharacter = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.playercharacter_, this_._impl_.playercharacter_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.NMT_Welcome)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NMT_Welcome::ByteSizeLong(const MessageLite& base) {
          const NMT_Welcome& this_ = static_cast<const NMT_Welcome&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NMT_Welcome::ByteSizeLong() const {
          const NMT_Welcome& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.NMT_Welcome)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string GameName = 1;
            if (!this_._internal_gamename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_gamename());
            }
            // string WorldName = 2;
            if (!this_._internal_worldname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_worldname());
            }
          }
           {
            // .GameProtocol.Character PlayerCharacter = 3;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.playercharacter_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NMT_Welcome::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NMT_Welcome*>(&to_msg);
  auto& from = static_cast<const NMT_Welcome&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.NMT_Welcome)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_gamename().empty()) {
    _this->_internal_set_gamename(from._internal_gamename());
  }
  if (!from._internal_worldname().empty()) {
    _this->_internal_set_worldname(from._internal_worldname());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.playercharacter_ != nullptr);
    if (_this->_impl_.playercharacter_ == nullptr) {
      _this->_impl_.playercharacter_ =
          ::google::protobuf::Message::CopyConstruct<::GameProtocol::Character>(arena, *from._impl_.playercharacter_);
    } else {
      _this->_impl_.playercharacter_->MergeFrom(*from._impl_.playercharacter_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NMT_Welcome::CopyFrom(const NMT_Welcome& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.NMT_Welcome)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NMT_Welcome::InternalSwap(NMT_Welcome* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.gamename_, &other->_impl_.gamename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.worldname_, &other->_impl_.worldname_, arena);
  swap(_impl_.playercharacter_, other->_impl_.playercharacter_);
}

::google::protobuf::Metadata NMT_Welcome::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NMT_Join::_Internal {
 public:
};

NMT_Join::NMT_Join(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.NMT_Join)
}
NMT_Join::NMT_Join(
    ::google::protobuf::Arena* arena, const NMT_Join& from)
    : NMT_Join(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE NMT_Join::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void NMT_Join::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.response_ = {};
}
NMT_Join::~NMT_Join() {
  // @@protoc_insertion_point(destructor:GameProtocol.NMT_Join)
  SharedDtor(*this);
}
inline void NMT_Join::SharedDtor(MessageLite& self) {
  NMT_Join& this_ = static_cast<NMT_Join&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* NMT_Join::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NMT_Join(arena);
}
constexpr auto NMT_Join::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NMT_Join),
                                            alignof(NMT_Join));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NMT_Join::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NMT_Join_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NMT_Join::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NMT_Join>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NMT_Join::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NMT_Join>(), &NMT_Join::ByteSizeLong,
            &NMT_Join::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NMT_Join, _impl_._cached_size_),
        false,
    },
    &NMT_Join::kDescriptorMethods,
    &descriptor_table_ControlProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NMT_Join::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> NMT_Join::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::NMT_Join>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 Response = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NMT_Join, _impl_.response_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Join, _impl_.response_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 Response = 1;
    {PROTOBUF_FIELD_OFFSET(NMT_Join, _impl_.response_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void NMT_Join::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.NMT_Join)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.response_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NMT_Join::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NMT_Join& this_ = static_cast<const NMT_Join&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NMT_Join::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NMT_Join& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.NMT_Join)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 Response = 1;
          if (this_._internal_response() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_response(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.NMT_Join)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NMT_Join::ByteSizeLong(const MessageLite& base) {
          const NMT_Join& this_ = static_cast<const NMT_Join&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NMT_Join::ByteSizeLong() const {
          const NMT_Join& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.NMT_Join)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 Response = 1;
            if (this_._internal_response() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_response());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NMT_Join::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NMT_Join*>(&to_msg);
  auto& from = static_cast<const NMT_Join&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.NMT_Join)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_response() != 0) {
    _this->_impl_.response_ = from._impl_.response_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NMT_Join::CopyFrom(const NMT_Join& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.NMT_Join)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NMT_Join::InternalSwap(NMT_Join* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.response_, other->_impl_.response_);
}

::google::protobuf::Metadata NMT_Join::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NMT_NetSpeed::_Internal {
 public:
};

NMT_NetSpeed::NMT_NetSpeed(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.NMT_NetSpeed)
}
NMT_NetSpeed::NMT_NetSpeed(
    ::google::protobuf::Arena* arena, const NMT_NetSpeed& from)
    : NMT_NetSpeed(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE NMT_NetSpeed::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void NMT_NetSpeed::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.lastackedpackettime_ = {};
}
NMT_NetSpeed::~NMT_NetSpeed() {
  // @@protoc_insertion_point(destructor:GameProtocol.NMT_NetSpeed)
  SharedDtor(*this);
}
inline void NMT_NetSpeed::SharedDtor(MessageLite& self) {
  NMT_NetSpeed& this_ = static_cast<NMT_NetSpeed&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* NMT_NetSpeed::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NMT_NetSpeed(arena);
}
constexpr auto NMT_NetSpeed::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NMT_NetSpeed),
                                            alignof(NMT_NetSpeed));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NMT_NetSpeed::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NMT_NetSpeed_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NMT_NetSpeed::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NMT_NetSpeed>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NMT_NetSpeed::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NMT_NetSpeed>(), &NMT_NetSpeed::ByteSizeLong,
            &NMT_NetSpeed::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NMT_NetSpeed, _impl_._cached_size_),
        false,
    },
    &NMT_NetSpeed::kDescriptorMethods,
    &descriptor_table_ControlProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NMT_NetSpeed::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> NMT_NetSpeed::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::NMT_NetSpeed>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 LastAckedPacketTime = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(NMT_NetSpeed, _impl_.lastackedpackettime_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_NetSpeed, _impl_.lastackedpackettime_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 LastAckedPacketTime = 1;
    {PROTOBUF_FIELD_OFFSET(NMT_NetSpeed, _impl_.lastackedpackettime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void NMT_NetSpeed::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.NMT_NetSpeed)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.lastackedpackettime_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NMT_NetSpeed::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NMT_NetSpeed& this_ = static_cast<const NMT_NetSpeed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NMT_NetSpeed::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NMT_NetSpeed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.NMT_NetSpeed)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 LastAckedPacketTime = 1;
          if (this_._internal_lastackedpackettime() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_lastackedpackettime(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.NMT_NetSpeed)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NMT_NetSpeed::ByteSizeLong(const MessageLite& base) {
          const NMT_NetSpeed& this_ = static_cast<const NMT_NetSpeed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NMT_NetSpeed::ByteSizeLong() const {
          const NMT_NetSpeed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.NMT_NetSpeed)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 LastAckedPacketTime = 1;
            if (this_._internal_lastackedpackettime() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_lastackedpackettime());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NMT_NetSpeed::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NMT_NetSpeed*>(&to_msg);
  auto& from = static_cast<const NMT_NetSpeed&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.NMT_NetSpeed)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_lastackedpackettime() != 0) {
    _this->_impl_.lastackedpackettime_ = from._impl_.lastackedpackettime_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NMT_NetSpeed::CopyFrom(const NMT_NetSpeed& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.NMT_NetSpeed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NMT_NetSpeed::InternalSwap(NMT_NetSpeed* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.lastackedpackettime_, other->_impl_.lastackedpackettime_);
}

::google::protobuf::Metadata NMT_NetSpeed::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NMT_Failure::_Internal {
 public:
};

NMT_Failure::NMT_Failure(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GameProtocol.NMT_Failure)
}
NMT_Failure::NMT_Failure(
    ::google::protobuf::Arena* arena, const NMT_Failure& from)
    : NMT_Failure(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE NMT_Failure::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void NMT_Failure::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, errortype_),
           0,
           offsetof(Impl_, errornum_) -
               offsetof(Impl_, errortype_) +
               sizeof(Impl_::errornum_));
}
NMT_Failure::~NMT_Failure() {
  // @@protoc_insertion_point(destructor:GameProtocol.NMT_Failure)
  SharedDtor(*this);
}
inline void NMT_Failure::SharedDtor(MessageLite& self) {
  NMT_Failure& this_ = static_cast<NMT_Failure&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* NMT_Failure::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NMT_Failure(arena);
}
constexpr auto NMT_Failure::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NMT_Failure),
                                            alignof(NMT_Failure));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NMT_Failure::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NMT_Failure_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NMT_Failure::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NMT_Failure>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NMT_Failure::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NMT_Failure>(), &NMT_Failure::ByteSizeLong,
            &NMT_Failure::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NMT_Failure, _impl_._cached_size_),
        false,
    },
    &NMT_Failure::kDescriptorMethods,
    &descriptor_table_ControlProtocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NMT_Failure::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> NMT_Failure::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GameProtocol::NMT_Failure>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 ErrorNum = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NMT_Failure, _impl_.errornum_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Failure, _impl_.errornum_)}},
    // int32 ErrorType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NMT_Failure, _impl_.errortype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NMT_Failure, _impl_.errortype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ErrorType = 1;
    {PROTOBUF_FIELD_OFFSET(NMT_Failure, _impl_.errortype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 ErrorNum = 2;
    {PROTOBUF_FIELD_OFFSET(NMT_Failure, _impl_.errornum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void NMT_Failure::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProtocol.NMT_Failure)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.errortype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.errornum_) -
      reinterpret_cast<char*>(&_impl_.errortype_)) + sizeof(_impl_.errornum_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NMT_Failure::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NMT_Failure& this_ = static_cast<const NMT_Failure&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NMT_Failure::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NMT_Failure& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GameProtocol.NMT_Failure)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 ErrorType = 1;
          if (this_._internal_errortype() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_errortype(), target);
          }

          // int32 ErrorNum = 2;
          if (this_._internal_errornum() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_errornum(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GameProtocol.NMT_Failure)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NMT_Failure::ByteSizeLong(const MessageLite& base) {
          const NMT_Failure& this_ = static_cast<const NMT_Failure&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NMT_Failure::ByteSizeLong() const {
          const NMT_Failure& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GameProtocol.NMT_Failure)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 ErrorType = 1;
            if (this_._internal_errortype() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_errortype());
            }
            // int32 ErrorNum = 2;
            if (this_._internal_errornum() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_errornum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NMT_Failure::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NMT_Failure*>(&to_msg);
  auto& from = static_cast<const NMT_Failure&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GameProtocol.NMT_Failure)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_errortype() != 0) {
    _this->_impl_.errortype_ = from._impl_.errortype_;
  }
  if (from._internal_errornum() != 0) {
    _this->_impl_.errornum_ = from._impl_.errornum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NMT_Failure::CopyFrom(const NMT_Failure& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProtocol.NMT_Failure)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NMT_Failure::InternalSwap(NMT_Failure* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NMT_Failure, _impl_.errornum_)
      + sizeof(NMT_Failure::_impl_.errornum_)
      - PROTOBUF_FIELD_OFFSET(NMT_Failure, _impl_.errortype_)>(
          reinterpret_cast<char*>(&_impl_.errortype_),
          reinterpret_cast<char*>(&other->_impl_.errortype_));
}

::google::protobuf::Metadata NMT_Failure::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GameProtocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ControlProtocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
